// Generated by tool/versioning.dart. Do not edit.
#pragma once
#define IMAGEHUB_PLATFORM_VERSION_NUMBER 0,1,0,1
#define IMAGEHUB_PLATFORM_VERSION_STRING "0.1.0+1"
#define IMAGEHUB_KERNEL_VERSION_STRING "0.1.0+1"
