// Autogenerated from Pigeon (v29.0.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.imagehost.imagehost

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object AndroidFilesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class AndroidIoCode(val raw: Int) {
  OK(0),
  CANCELLED(1),
  PERMISSION_DENIED(2),
  SOURCE_MISSING(3),
  CLOUD_PENDING(4),
  UNAVAILABLE(5),
  INVALID_INPUT(6),
  INPUT_CHANGED(7),
  UNSUPPORTED(8),
  STORAGE(9),
  CLEANUP_PENDING(10),
  UNCONFIRMED(11);

  companion object {
    fun ofRaw(raw: Int): AndroidIoCode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class AndroidDestinationKind(val raw: Int) {
  DOCUMENT(0),
  TREE(1),
  PHOTOS(2);

  companion object {
    fun ofRaw(raw: Int): AndroidDestinationKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AndroidPickedResource (
  val handle: String,
  val displayName: String,
  val sourceType: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidPickedResource {
      val handle = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      val sourceType = pigeonVar_list[2] as String
      return AndroidPickedResource(handle, displayName, sourceType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      handle,
      displayName,
      sourceType,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidPickedResource
    return AndroidFilesPigeonUtils.deepEquals(this.handle, other.handle) && AndroidFilesPigeonUtils.deepEquals(this.displayName, other.displayName) && AndroidFilesPigeonUtils.deepEquals(this.sourceType, other.sourceType)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.handle)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.displayName)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.sourceType)
    return result
  }
  override fun toString(): String {
    return "AndroidPickedResource(handle=$handle, displayName=$displayName, sourceType=$sourceType)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AndroidSelection (
  val cancelled: Boolean,
  val resources: List<AndroidPickedResource>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidSelection {
      val cancelled = pigeonVar_list[0] as Boolean
      val resources = pigeonVar_list[1] as List<AndroidPickedResource>
      return AndroidSelection(cancelled, resources)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cancelled,
      resources,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidSelection
    return AndroidFilesPigeonUtils.deepEquals(this.cancelled, other.cancelled) && AndroidFilesPigeonUtils.deepEquals(this.resources, other.resources)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.cancelled)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.resources)
    return result
  }
  override fun toString(): String {
    return "AndroidSelection(cancelled=$cancelled, resources=$resources)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AndroidReadReply (
  val code: AndroidIoCode,
  val bytes: ByteArray,
  val eof: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidReadReply {
      val code = pigeonVar_list[0] as AndroidIoCode
      val bytes = pigeonVar_list[1] as ByteArray
      val eof = pigeonVar_list[2] as Boolean
      return AndroidReadReply(code, bytes, eof)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      bytes,
      eof,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidReadReply
    return AndroidFilesPigeonUtils.deepEquals(this.code, other.code) && AndroidFilesPigeonUtils.deepEquals(this.bytes, other.bytes) && AndroidFilesPigeonUtils.deepEquals(this.eof, other.eof)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.code)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.bytes)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.eof)
    return result
  }
  override fun toString(): String {
    return "AndroidReadReply(code=$code, bytes=${bytes.contentToString()}, eof=$eof)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AndroidDestination (
  val cancelled: Boolean,
  val handle: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidDestination {
      val cancelled = pigeonVar_list[0] as Boolean
      val handle = pigeonVar_list[1] as String?
      return AndroidDestination(cancelled, handle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cancelled,
      handle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidDestination
    return AndroidFilesPigeonUtils.deepEquals(this.cancelled, other.cancelled) && AndroidFilesPigeonUtils.deepEquals(this.handle, other.handle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.cancelled)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.handle)
    return result
  }
  override fun toString(): String {
    return "AndroidDestination(cancelled=$cancelled, handle=$handle)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AndroidExportRequest (
  val operationId: String,
  val sourcePath: String,
  val displayName: String,
  val mimeType: String,
  val sha256: String,
  val byteCount: Long,
  val kind: AndroidDestinationKind,
  val destinationHandle: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidExportRequest {
      val operationId = pigeonVar_list[0] as String
      val sourcePath = pigeonVar_list[1] as String
      val displayName = pigeonVar_list[2] as String
      val mimeType = pigeonVar_list[3] as String
      val sha256 = pigeonVar_list[4] as String
      val byteCount = pigeonVar_list[5] as Long
      val kind = pigeonVar_list[6] as AndroidDestinationKind
      val destinationHandle = pigeonVar_list[7] as String?
      return AndroidExportRequest(operationId, sourcePath, displayName, mimeType, sha256, byteCount, kind, destinationHandle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      operationId,
      sourcePath,
      displayName,
      mimeType,
      sha256,
      byteCount,
      kind,
      destinationHandle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidExportRequest
    return AndroidFilesPigeonUtils.deepEquals(this.operationId, other.operationId) && AndroidFilesPigeonUtils.deepEquals(this.sourcePath, other.sourcePath) && AndroidFilesPigeonUtils.deepEquals(this.displayName, other.displayName) && AndroidFilesPigeonUtils.deepEquals(this.mimeType, other.mimeType) && AndroidFilesPigeonUtils.deepEquals(this.sha256, other.sha256) && AndroidFilesPigeonUtils.deepEquals(this.byteCount, other.byteCount) && AndroidFilesPigeonUtils.deepEquals(this.kind, other.kind) && AndroidFilesPigeonUtils.deepEquals(this.destinationHandle, other.destinationHandle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.operationId)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.sourcePath)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.displayName)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.mimeType)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.sha256)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.byteCount)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.kind)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.destinationHandle)
    return result
  }
  override fun toString(): String {
    return "AndroidExportRequest(operationId=$operationId, sourcePath=$sourcePath, displayName=$displayName, mimeType=$mimeType, sha256=$sha256, byteCount=$byteCount, kind=$kind, destinationHandle=$destinationHandle)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AndroidExportReply (
  val code: AndroidIoCode,
  val uri: String? = null,
  val displayName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AndroidExportReply {
      val code = pigeonVar_list[0] as AndroidIoCode
      val uri = pigeonVar_list[1] as String?
      val displayName = pigeonVar_list[2] as String?
      return AndroidExportReply(code, uri, displayName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      uri,
      displayName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AndroidExportReply
    return AndroidFilesPigeonUtils.deepEquals(this.code, other.code) && AndroidFilesPigeonUtils.deepEquals(this.uri, other.uri) && AndroidFilesPigeonUtils.deepEquals(this.displayName, other.displayName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.code)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.uri)
    result = 31 * result + AndroidFilesPigeonUtils.deepHash(this.displayName)
    return result
  }
  override fun toString(): String {
    return "AndroidExportReply(code=$code, uri=$uri, displayName=$displayName)"
  }
}
private open class AndroidFilesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AndroidIoCode.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AndroidDestinationKind.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidPickedResource.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidSelection.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidReadReply.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidDestination.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidExportRequest.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AndroidExportReply.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is AndroidIoCode -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is AndroidDestinationKind -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is AndroidPickedResource -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AndroidSelection -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is AndroidReadReply -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is AndroidDestination -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is AndroidExportRequest -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is AndroidExportReply -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AndroidResourceHost {
  fun pickResources(photos: Boolean, backup: Boolean, callback: (Result<AndroidSelection>) -> Unit)
  fun recoverSelection(callback: (Result<AndroidSelection>) -> Unit)
  fun readResource(handle: String, callback: (Result<AndroidReadReply>) -> Unit)
  fun closeResource(handle: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by AndroidResourceHost. */
    val codec: MessageCodec<Any?> by lazy {
      AndroidFilesPigeonCodec()
    }
    /** Sets up an instance of `AndroidResourceHost` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AndroidResourceHost?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.imagehost.AndroidResourceHost.pickResources$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val photosArg = args[0] as Boolean
            val backupArg = args[1] as Boolean
            api.pickResources(photosArg, backupArg) { result: Result<AndroidSelection> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AndroidFilesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AndroidFilesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.imagehost.AndroidResourceHost.recoverSelection$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.recoverSelection{ result: Result<AndroidSelection> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AndroidFilesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AndroidFilesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.imagehost.AndroidResourceHost.readResource$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as String
            api.readResource(handleArg) { result: Result<AndroidReadReply> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AndroidFilesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AndroidFilesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.imagehost.AndroidResourceHost.closeResource$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as String
            api.closeResource(handleArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AndroidFilesPigeonUtils.wrapError(error))
              } else {
                reply.reply(AndroidFilesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AndroidExportHost {
  fun createDocument(displayName: String, mimeType: String, callback: (Result<AndroidDestination>) -> Unit)
  fun pickDirectory(operationIds: List<String>, callback: (Result<AndroidDestination>) -> Unit)
  fun closeDestination(handle: String, callback: (Result<Unit>) -> Unit)
  fun exportFile(request: AndroidExportRequest, callback: (Result<AndroidExportReply>) -> Unit)
  fun cancelExport(operationId: String)

  companion object {
    /** The codec used by AndroidExportHost. */
    val codec: MessageCodec<Any?> by lazy {
      AndroidFilesPigeonCodec()
    }
    /** Sets up an instance of `AndroidExportHost` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AndroidExportHost?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.imagehost.AndroidExportHost.createDocument$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val displayNameArg = args[0] as String
            val mimeTypeArg = args[1] as String
            api.createDocument(displayNameArg, mimeTypeArg) { result: Result<AndroidDestination> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AndroidFilesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AndroidFilesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.imagehost.AndroidExportHost.pickDirectory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val operationIdsArg = args[0] as List<String>
            api.pickDirectory(operationIdsArg) { result: Result<AndroidDestination> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AndroidFilesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AndroidFilesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.imagehost.AndroidExportHost.closeDestination$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as String
            api.closeDestination(handleArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AndroidFilesPigeonUtils.wrapError(error))
              } else {
                reply.reply(AndroidFilesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.imagehost.AndroidExportHost.exportFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as AndroidExportRequest
            api.exportFile(requestArg) { result: Result<AndroidExportReply> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(AndroidFilesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(AndroidFilesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.imagehost.AndroidExportHost.cancelExport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val operationIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancelExport(operationIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              AndroidFilesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
