/* UI-only prototype. All product operations use in-memory synthetic fixtures.
   No real files, credentials, network uploads, cloud accounts or app data. */
(() => {
  'use strict';
  const root = document.getElementById('root');
  const scheme = 'a';
  const params = new URLSearchParams(location.search);
  const schemeNames = {a:'清简'};
  const pageNames = {library:'我的图库',editor:'图片处理',tasks:'上传任务',accounts:'图床账号',settings:'设置',more:'更多',recycle:'回收区'};
  const paths = {
    library:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
    image:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 5-5 4 4 4-6 5 7"/>',
    editor:'<path d="M7 3v14h14M3 7h14v14M14 3v4M3 14h4"/>',
    tasks:'<path d="M8 5h13M8 12h13M8 19h13"/><path d="m2 5 1 1 2-2m-3 8 1 1 2-2m-3 8 1 1 2-2"/>',
    accounts:'<path d="M6 17h12a4 4 0 0 0 .5-8A6.5 6.5 0 0 0 6 8a4.5 4.5 0 0 0 0 9Z"/>',
    settings:'<path d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z"/><path d="m9 3-1 3-3 1 1 3-3 2 3 2-1 3 3 1 1 3h6l1-3 3-1-1-3 3-2-3-2 1-3-3-1-1-3Z"/>',
    more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
    plus:'<path d="M12 5v14M5 12h14"/>', search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',
    upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 15v5h16v-5"/>',download:'<path d="M12 3v13m-5-5 5 5 5-5M4 17v4h16v-4"/>',
    check:'<path d="m5 12 4 4L19 6"/>', close:'<path d="m6 6 12 12M18 6 6 18"/>',
    arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',back:'<path d="M20 12H4m6-6-6 6 6 6"/>',
    star:'<path d="m12 3 2.8 5.8 6.4.9-4.6 4.5 1.1 6.3L12 17.5l-5.7 3 1.1-6.3L2.8 9.7l6.4-.9Z"/>',
    link:'<path d="m10 14 4-4M8 16l-1 1a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m0 2 1-1a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0"/>',
    copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',
    trash:'<path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/>',
    folder:'<path d="M3 7V4h7l2 3h9v13H3Z"/>',filter:'<path d="M4 5h16l-6 7v6l-4 2v-8Z"/>',
    list:'<path d="M8 5h13M8 12h13M8 19h13M3 5h1M3 12h1M3 19h1"/>',
    info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',
    warning:'<path d="m12 3 10 18H2Z"/><path d="M12 9v5M12 17h.01"/>',
    refresh:'<path d="M20 7a9 9 0 1 0 1 9M20 2v5h-5"/>',
    shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',
    local:'<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4"/>',
    moon:'<path d="M20 14A9 9 0 0 1 10 3 9 9 0 1 0 20 14Z"/>',
    pause:'<path d="M8 5v14M16 5v14"/>',play:'<path d="m7 4 13 8-13 8Z"/>',
    tag:'<path d="M3 3h8l10 10-8 8L3 11Z"/><circle cx="7" cy="7" r="1"/>',
    lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',
    clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
    broken:'<rect x="3" y="3" width="18" height="18" rx="2"/><path d="m3 17 4-4 4 3m4-3 6 4M3 3l18 18"/>',
    sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2m-3-9-1 1M6 18l-1 1M5 5l1 1m12 12 1 1"/>'
  };
  const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name] || paths.info}</svg>`;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const btn = (label,action,kind='',ico='',extra='') => `<button type="button" class="btn ${kind}" data-action="${action}" ${extra}>${ico ? icon(ico) : ''}${label}</button>`;
  const pill = (text,kind='',ico='') => `<span class="pill ${kind}">${ico ? icon(ico) : ''}${esc(text)}</span>`;
  const notice = (text,kind='',ico='info') => `<div class="notice ${kind}">${icon(ico)}<div>${text}</div></div>`;
  const fixtures = () => [
    {id:1,name:'海岸线 · 午后.jpg',sprite:0,format:'JPEG',size:'3.8 MB',width:3024,height:2016,category:'旅行',tags:['海岸','夏日'],favorite:true,links:['Catbox'],partial:true,available:true},
    {id:2,name:'暖墙与树影.jpg',sprite:1,format:'JPEG',size:'2.4 MB',width:2400,height:3000,category:'素材',tags:['建筑','光影'],favorite:false,links:['Catbox','ImgBB'],available:true},
    {id:3,name:'一枝绿意.png',sprite:2,format:'PNG',size:'4.1 MB',width:2000,height:2500,category:'日常',tags:['静物'],favorite:true,links:[],available:true},
    {id:4,name:'山间湖泊.webp',sprite:3,format:'WebP',size:'1.8 MB',width:3600,height:2400,category:'旅行',tags:['山野'],favorite:false,links:['Catbox'],available:true},
    {id:5,name:'柠檬与水杯.jpg',sprite:4,format:'JPEG',size:'2.1 MB',width:2500,height:2500,category:'日常',tags:['静物','光影'],favorite:false,links:[],available:true},
    {id:6,name:'旋转楼梯_用于文章封面_最终选定版本_2026年10月.png',sprite:5,format:'PNG',size:'5.6 MB',width:3200,height:4000,category:'素材',tags:['建筑'],favorite:false,links:['ImgBB'],available:true},
    {id:7,name:'一杯咖啡.jpg',sprite:6,format:'JPEG',size:'2.7 MB',width:2800,height:2800,category:'日常',tags:['生活'],favorite:true,links:[],available:true},
    {id:8,name:'沙丘 · 傍晚.jpg',sprite:7,format:'JPEG',size:'3.2 MB',width:4000,height:2600,category:'旅行',tags:['沙漠'],favorite:false,links:[],available:true},
    {id:9,name:'林间微光.bmp',sprite:8,format:'BMP',size:'8.2 MB',width:1600,height:1600,category:'素材',tags:['植物'],favorite:false,links:[],available:true}
  ];
  const tasksFixture = () => [
    {id:'t1',name:'文章配图',time:'今天 14:32',paused:false,items:[{asset:1,target:'Catbox · 匿名',state:'succeeded'},{asset:1,target:'ImgBB · 写作',state:'failed',reason:'授权失效'},{asset:2,target:'Catbox · 匿名',state:'succeeded'},{asset:2,target:'ImgBB · 写作',state:'succeeded'}]},
    {id:'t2',name:'旅行照片',time:'今天 14:26',paused:false,items:[{asset:4,target:'Catbox · 匿名',state:'unknown',reason:'提交后连接中断，未收到确认'}]},
    {id:'t3',name:'日常素材',time:'今天 14:35',paused:false,items:[{asset:7,target:'Catbox · 匿名',state:'running',progress:62},{asset:7,target:'ImgBB · 写作',state:'waiting',reason:'等待前一项释放并发位置'}]}
  ];
  const s = {page:pageNames[params.get('page')] ? params.get('page') : 'library',scenario:params.get('scenario') || 'normal',images:fixtures(),tasks:tasksFixture(),selected:new Set(),focus:1,filter:'all',category:'all',availability:'all',query:'',sort:'import',view:'grid',operation:'compress',format:'WebP',policy:'size',quality:85,longest:1600,ratio:'3:2',gap:0,stitchOrder:[1,2],output:null,modal:null,toast:'',dark:params.get('theme') === 'dark',accountState:'expired',accountOverrides:{},extraAccounts:[],crop:{x:300,y:200,w:1800,h:1200},stitchLayout:'横向',background:'白色',preferences:{network:'unmetered',retention:'24',concurrency:'3'},draftPreferences:{network:'unmetered',retention:'24',concurrency:'3'},settingSaved:false,cacheCleaned:false,backupType:'full',restored:false};
  let toastTimer;
  const image = id => s.images.find(p => p.id === id) || s.images[0] || fixtures()[0];
  const photo = (p,cl='',flag=false) => `<div role="img" aria-label="${esc(p.name)}${p.available ? '' : '，本机副本缺失'}" class="photo ${cl} ${p.available ? '' : 'missing'}" style="--x:${p.sprite%3*50}%;--y:${Math.floor(p.sprite/3)*50}%">${p.available ? '' : icon('broken')}${flag ? `<span class="image-flag">${icon(!p.available ? 'warning' : p.partial ? 'warning' : p.links.length ? 'check' : 'local')}${!p.available ? '副本缺失' : p.partial ? '部分上传成功' : p.links.length ? `已上传 ${p.links.length} 个目标` : '仅本机'}</span>` : ''}</div>`;
  const filtered = () => {
    let out=s.images.filter(p => Boolean(p.recycled) === (s.page === 'recycle'));
    if (s.filter==='favorites') out=out.filter(p=>p.favorite);
    if (s.filter==='notuploaded') out=out.filter(p=>!p.links.length);
    if (s.category!=='all') out=out.filter(p=>p.category===s.category);
    if (s.availability!=='all') out=out.filter(p=>s.availability==='available' ? p.available : !p.available);
    if (s.query.trim()) {const q=s.query.trim().normalize('NFC').toLocaleLowerCase();out=out.filter(p=>[p.name,p.format,p.category,...p.tags,...p.links].join(' ').toLocaleLowerCase().includes(q));}
    if(s.sort==='name') out.sort((a,b)=>a.name.localeCompare(b.name,'zh-CN') || a.id-b.id);
    else if(s.sort==='size'){const bytes=p=>parseFloat(p.size)*(p.size.includes('MB')?1024*1024:1024);out.sort((a,b)=>bytes(b)-bytes(a)||a.id-b.id);}
    else out.sort((a,b)=>a.id-b.id);
    return out;
  };
  const stateText={succeeded:'已成功',failed:'失败',unknown:'待确认',running:'上传中',waiting:'等待中',paused:'已暂停',cancelled:'已取消'};
  const stateKind={succeeded:'ok',failed:'bad',unknown:'warn',running:'accent',waiting:'',cancelled:''};
  const aggregate = task => {const a=task.items.map(x=>x.state);if(a.some(x=>x==='running'||x==='waiting'))return task.paused&&!a.includes('running') ? '已暂停' : '进行中';if(a.includes('unknown'))return '待确认';if(a.every(x=>x==='succeeded'))return '全部成功';if(a.includes('succeeded'))return '部分成功';if(a.includes('cancelled'))return '已取消';return '全部失败';};
  const counts = items => items.reduce((o,x)=>(o[x.state]=(o[x.state]||0)+1,o),{});
  const selectedImages=()=>s.images.filter(p=>s.selected.has(p.id));
  const createOutput = () => {
    const p=image(s.focus), op=s.operation, format=s.format;
    let width=p.width,height=p.height;
    if(op==='compress'&&s.policy==='size'){const factor=Math.min(1,s.longest/Math.max(width,height));width=Math.max(1,Math.round(width*factor));height=Math.max(1,Math.round(height*factor));}
    if(op==='crop'){width=Number(document.getElementById('crop-w').value);height=Number(document.getElementById('crop-h').value);}
    const layout=document.getElementById('stitch-layout')?.value;
    if(op==='stitch'){const pics=s.stitchOrder.map(image),gap=s.gap;
      if(layout==='横向'){width=pics.reduce((a,b)=>a+b.width,0)+(pics.length-1)*gap;height=Math.max(...pics.map(x=>x.height));}
      else if(layout==='纵向'){height=pics.reduce((a,b)=>a+b.height,0)+(pics.length-1)*gap;width=Math.max(...pics.map(x=>x.width));}
      else{const cols=Math.ceil(Math.sqrt(pics.length)),rows=Math.ceil(pics.length/cols);width=cols*Math.max(...pics.map(x=>x.width))+(cols-1)*gap;height=rows*Math.max(...pics.map(x=>x.height))+(rows-1)*gap;}
    }
    return {saved:false,larger:s.scenario==='larger',inputId:p.id,inputName:p.name,inputSize:p.size,inputWidth:p.width,inputHeight:p.height,inputFormat:p.format,format,width,height,operation:op,quality:s.quality,longest:s.longest,size:s.scenario==='larger'?'4.6 MB':'824 KB',name:p.name.replace(/\.[^.]+$/,'')+'_处理结果.'+(format==='JPEG'?'jpg':format.toLowerCase()),ids:op==='stitch'?[...s.stitchOrder]:[p.id],layout};
  };
  const scenarioOptions=[['normal','常规状态'],['empty','空图库'],['loading','加载中'],['load-error','加载失败'],['missing','副本缺失'],['offline','离线等待'],['unknown','上传待确认'],['process-error','处理失败'],['budget','处理超预算'],['save-error','保存失败'],['permission','导出授权拒绝'],['larger','处理后更大'],['low-space','空间不足']];
  const toolbar = () => `<div class="sample-strip"><div class="row"><a href="../index.html">${icon("back")}</a><strong>桌面 A · 设计参考</strong></div><div class="row"><label class="sr-only" for="scenario">演示状态</label><select id="scenario">${scenarioOptions.map(([v,n])=>`<option value="${v}" ${s.scenario===v?"selected":""}>${n}</option>`).join("")}</select>${btn("重置","reset","")}</div></div><div class="sample-caption">桌面参考 · 操作均为模拟<a href="design-spec.md">设计说明 ↗</a><a href="../mobile/index.html">手机 M1 / M2 ↗</a></div>`;
  const navButton = (page,label='') => `<button class="nav-btn ${s.page===page || page==='library'&&s.page==='recycle' ? 'active' : ''}" data-action="page" data-page="${page}" ${s.page===page?'aria-current="page"':''}>${icon(page)}<span class="nav-label">${label || pageNames[page]}</span>${page==='tasks'?`<span class="nav-count">${s.tasks.length}</span>`:''}</button>`;
  const nav = () => ['library','editor','tasks','accounts','settings'].map(p=>navButton(p,p==='library'?'图库':p==='editor'?'处理':p==='tasks'?'任务':pageNames[p])).join('');
  const brand=()=>`<div class="brand"><span class="brand-mark">${icon('image')}</span><span class="brand-text">ImageHost</span></div>`;
  const searchBox=id=>`<div class="searchbox">${icon('search')}<label for="${id}" class="sr-only">搜索图片、标签或图床</label><input id="${id}" data-input="query" value="${esc(s.query)}" placeholder="搜索图片、标签或图床" autocomplete="off"><span class="key">/</span></div>`;
  const shell = content => `${toolbar()}<div class="workbench"><aside class="sidebar">${brand()}<nav class="nav" aria-label="主导航">${nav()}</nav><div class="side-section"><p>整理</p><button class="side-link" data-action="favorites">${icon('star')}收藏</button>${['旅行','素材','日常'].map((n,i)=>`<button class="side-link" data-action="category" data-value="${n}"><span class="side-dot ${i===1?'sand':i===2?'green':''}"></span>${n}</button>`).join('')}<button class="side-link" data-action="page" data-page="recycle">${icon('trash')}回收区</button></div><div class="side-bottom"><div class="local-note">${icon('local')}<span>本机图库 · 无需登录</span></div></div></aside><section class="main"><header class="topnav">${brand()}<nav class="nav" aria-label="顶部导航">${nav()}</nav>${btn(s.dark?'浅色':'深色','theme','quiet square',s.dark?'sun':'moon',`aria-label="切换${s.dark?'浅色':'深色'}主题"`)}</header><header class="masthead"><div class="breadcrumb"><span>本机图库</span>${icon('arrow')}<span class="page-crumb">${pageNames[s.page]}</span></div><div class="row">${s.page==='library'||s.page==='recycle'?searchBox('search-desktop'):''}<span class="local-pill pill">${icon('local')}本地模式</span>${btn('','theme','quiet square',s.dark?'sun':'moon',`aria-label="切换${s.dark?'浅色':'深色'}主题"`)}</div></header><main class="page">${content}</main><footer class="statusbar"><span>${s.page==='library'?`${filtered().length} 张图片 · 本机副本独立保管`:'本地数据保留在这台设备'}</span><span>${s.scenario==='offline'?'当前离线 · 本地功能可用':'无应用云端账户'}</span></footer></section></div>${s.modal?modalHTML():''}${s.toast?`<div class="toast" role="status">${esc(s.toast)}</div>`:''}`;
  const pageTitle=(title,sub,actions='')=>`<div class="page-title"><div><span class="eyebrow">IMAGEHOST / ${scheme.toUpperCase()}</span><h1>${title}</h1><p>${sub}</p></div><div class="row">${actions}</div></div>`;
  const detail = p => `<div class="inspector-head"><span>图片详情</span>${btn('','detail','quiet square','more',`aria-label="打开完整图片详情" data-id="${p.id}"`)}</div>${photo(p)}<p class="detail-name">${esc(p.name)}</p>${pill(p.available?'本机副本可用':'本机副本缺失',p.available?'ok':'warn',p.available?'check':'warning')}<dl class="definition"><dt>格式</dt><dd>${p.format}</dd><dt>尺寸</dt><dd>${p.width} × ${p.height}</dd><dt>大小</dt><dd>${p.size}</dd><dt>导入时间</dt><dd>2026-10-03 14:18</dd><dt>来源</dt><dd>系统选图 · 独立副本</dd><dt>分类</dt><dd>${esc(p.category)}</dd></dl><div class="row">${p.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}${btn('编辑','tags','small quiet','tag',`data-id="${p.id}"`)}</div><hr class="line"><p class="section-heading">上传结果</p>${p.links.length ? p.links.map(t=>`<div class="result-line"><span>${t}</span>${pill('有链接','ok','check')}</div>`).join('') : '<small>还没有上传结果</small>'}${p.partial?`<div class="result-line"><span>ImgBB · 写作</span>${pill('授权失效','bad')}</div>`:''}${btn('查看链接','links','', 'link',`data-id="${p.id}" ${p.links.length?'':'disabled'}`)}${btn(p.available?'处理这张图片':'重新关联副本',p.available?'edit-image':'repair','quiet',p.available?'editor':'refresh',`data-id="${p.id}"`)}`;
  const grid=items=>`<div class="image-grid">${items.map(p=>`<article class="image-card ${s.focus===p.id?'focused':''} ${s.selected.has(p.id)?'selected':''}"><label class="checkwrap"><input type="checkbox" data-select="${p.id}" aria-label="选择 ${esc(p.name)}" ${s.selected.has(p.id)?'checked':''}></label><button class="photo-button" data-action="detail" data-id="${p.id}" aria-label="预览 ${esc(p.name)}">${photo(p,'',true)}${p.favorite?`<span class="favorite-mark">${icon('star')}</span>`:''}</button><div class="image-info"><span class="title" title="${esc(p.name)}">${esc(p.name)}</span><div class="meta"><span>${p.format} · ${p.size}</span><span>${p.width} × ${p.height}</span></div></div></article>`).join('')}</div>`;
  const table=items=>`<table class="table-view"><thead><tr><th><input type="checkbox" data-action="select-all" aria-label="选择当前筛选结果" ${items.length&&items.every(p=>s.selected.has(p.id))?'checked':''}></th><th>图片 / 名称</th><th>整理</th><th>上传结果</th><th>操作</th></tr></thead><tbody>${items.map(p=>`<tr class="${s.selected.has(p.id)?'selected':''}"><td><input type="checkbox" data-select="${p.id}" aria-label="选择 ${esc(p.name)}" ${s.selected.has(p.id)?'checked':''}></td><td><div class="file-row">${photo(p,'mini-photo')}<div class="grow"><button class="file-name truncate" data-action="detail" data-id="${p.id}" title="${esc(p.name)}">${esc(p.name)}</button><small>${p.format} · ${p.width} × ${p.height} · ${p.size}</small></div></div></td><td><span>${esc(p.category)}</span><div class="row">${p.tags.slice(0,2).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></td><td><div class="row">${!p.available?pill('副本缺失','warn'):p.partial?pill('部分成功','warn'):p.links.length?pill(`${p.links.length} 个目标成功`,'ok'):pill('仅本机')}${p.favorite?icon('star'):''}</div></td><td>${btn('','detail','quiet square','more',`data-id="${p.id}" aria-label="详情 ${esc(p.name)}"`)}</td></tr>`).join('')}</tbody></table>`;
  const selectionbar=()=>s.selected.size?`<div class="selectionbar"><span class="selected-count">已选 ${s.selected.size} 张${selectedImages().some(p=>!p.available)?' · 含缺失副本':''}</span>${btn(s.page==='recycle'?'恢复':'上传',s.page==='recycle'?'restore-images':'upload','primary small',s.page==='recycle'?'refresh':'upload')}${s.page==='recycle'?'':btn('处理','process-selected','small','editor')}${btn('整理','tags','small','tag')}${btn('','delete','small danger','trash','aria-label="移到回收区"')}${btn('取消选择','clear-selection','small quiet')}</div>`:'';
  function libraryPage(){
    const items=filtered();
    const action=s.page==='recycle'?btn('返回图库','page','', 'back','data-page="library"'):btn('导入图片','import','primary','plus');
    const title=s.page==='recycle'?'回收区':'我的图库';
    const intro=s.page==='recycle'?'移除的图片仍可恢复。到期后由你决定是否清理。':'整理、处理、发布，都从这里开始。';
    let content='';
    if(s.scenario==='load-error')content=`<div class="empty">${icon('warning')}<h2>图库暂时无法加载</h2><p>已保留现有数据。重试或查看诊断，不会创建空图库替换原内容。</p><div class="row">${btn('重新加载','resolve-scenario','primary','refresh')}${btn('查看诊断','diagnostic','','info')}</div></div>`;
    else if(s.scenario==='loading')content=`<div class="notice">${icon('clock')}<div>正在读取本机图库…</div></div><div class="skeleton-row" style="margin-top:20px">${Array.from({length:6},()=>'<div class="skeleton"></div>').join('')}</div>${btn('完成加载演示','resolve-scenario','quiet')}`;
    else if(!items.length)content=`<div class="empty">${icon(s.page==='recycle'?'trash':'image')}<h2>${s.query||s.filter!=='all'||s.category!=='all'?'没有符合条件的图片':s.page==='recycle'?'回收区是空的':'从第一张图片开始'}</h2><p>${s.query||s.filter!=='all'||s.category!=='all'?'试试其他关键词，或清除筛选条件。':'导入后保存独立的本机副本，原文件保留在原处。'}</p>${s.query||s.filter!=='all'||s.category!=='all'?btn('清除筛选','clear-filter','primary'):s.page==='recycle'?btn('返回图库','page','primary','','data-page="library"'):btn('导入图片','import','primary','plus')}</div>`;
    else content=`<div class="section-label"><span>${s.category==='all'?'今天 · 10 月 3 日':esc(s.category)} / ${items.length} 张</span><button class="backlink" data-action="select-all">选择当前结果</button></div>${s.view==='grid'?grid(items):table(items)}`;
    return `${pageTitle(title,intro,['loading','load-error'].includes(s.scenario)||!items.length&&!s.images.some(x=>Boolean(x.recycled)===(s.page==='recycle'))?'':action)}${s.scenario==='offline'?notice('当前离线。整理和处理可以继续，上传等待网络恢复。','warn'):s.scenario==='low-space'?notice('存储空间不足。新导入和处理暂停，已有图片仍可浏览。<br><button class="backlink" data-action="page" data-page="settings">管理存储空间 →</button>','warn'):''}<div class="library-layout ${!items.length?'no-inspector':''}"><section class="content"><div class="filterbar"><div class="tabs">${[['all','全部'],['favorites','收藏'],['notuploaded','未上传']].map(([v,n])=>`<button class="tab ${s.filter===v?'active':''}" data-action="filter" data-value="${v}" aria-pressed="${s.filter===v}">${n}</button>`).join('')}</div><div class="row">${btn('筛选','filters','small quiet','filter')}<label class="sr-only" for="sort">排序</label><select id="sort" style="width:113px;min-height:32px;padding:4px 7px;font-size:11px"><option value="import" ${s.sort==='import'?'selected':''}>导入时间</option><option value="name" ${s.sort==='name'?'selected':''}>名称</option><option value="size" ${s.sort==='size'?'selected':''}>文件大小</option></select><div class="view-switch">${btn('','grid','small quiet '+(s.view==='grid'?'active':''),'library','aria-label="网格视图"')}${btn('','list','small quiet '+(s.view==='list'?'active':''),'list','aria-label="列表视图"')}</div></div><div class="gallery-search">${searchBox('search-gallery')}</div></div>${s.category!=='all'||s.availability!=='all'?`<div class="row" style="margin-bottom:14px">${pill(s.category==='all'?'全部分类':s.category,'accent')}${s.availability!=='all'?pill(s.availability==='missing'?'副本缺失':'本机可用','accent'):''}${btn('清除','clear-filter','small quiet','close')}</div>`:''}${content}${selectionbar()}</section>${items.length?`<aside class="inspector" aria-label="选中图片详情">${detail(items.find(p=>p.id===s.focus)||items[0])}</aside>`:''}</div>`;
  }
  function editorPage(){
    const input=s.images.find(x=>x.id===s.focus&&!x.recycled);if(!input)return pageTitle('图片处理','请选择已保管的本机图片。')+`<div class="empty">${icon('image')}<h2>还没有可处理的图片</h2><p>先导入图片，或从图库选择有效输入。不会把展示素材当作已导入图片。</p>${btn('导入图片','import','primary','plus')}${s.images.some(x=>!x.recycled)?btn('选择图片','choose-input','','image'):''}</div>`;const p=input;const operationName={compress:'压缩',crop:'裁剪',stitch:'拼接'};
    const controls=s.operation==='compress'?`<label class="field"><span>处理策略</span><select id="policy"><option value="size" ${s.policy==='size'?'selected':''}>体积优先</option><option value="fidelity" ${s.policy==='fidelity'?'selected':''}>保真优先</option></select><small>${s.policy==='size'?'可调整尺寸与编码质量，不放大小图。':'保留尺寸与图片特征，不保证体积更小。'}</small></label><label class="field"><span>最长边 · 像素</span><input class="input" id="longest" type="number" min="1" max="16384" step="1" value="${s.longest}" ${s.policy==='fidelity'?'disabled':''}></label>`:s.operation==='crop'?`<label class="field"><span>裁剪比例</span><select id="ratio">${['3:2','1:1','4:3','自由'].map(x=>`<option ${s.ratio===x?'selected':''}>${x}</option>`).join('')}</select></label><div class="controls-grid"><label class="field"><span>起点 X</span><input class="input" id="crop-x" type="number" min="0" value="${s.crop.x}"></label><label class="field"><span>起点 Y</span><input class="input" id="crop-y" type="number" min="0" value="${s.crop.y}"></label><label class="field"><span>宽度</span><input class="input" id="crop-w" type="number" min="1" value="${s.crop.w}"></label><label class="field"><span>高度</span><input class="input" id="crop-h" type="number" min="1" value="${s.crop.h}"></label></div><small>单位为方向校正后的整数像素。输入与裁剪框同步仅作示意。</small>`:`<div class="stitch-strip">${s.stitchOrder.map((id,i)=>`<div class="stitch-item">${photo(image(id))}<div class="row">${i+1}${btn('←','stitch-left','quiet small','',`data-index="${i}" ${i===0?'disabled':''} aria-label="将第 ${i+1} 张向前移动"`)}${btn('→','stitch-right','quiet small','',`data-index="${i}" ${i===s.stitchOrder.length-1?'disabled':''} aria-label="将第 ${i+1} 张向后移动"`)}</div></div>`).join('')}</div><label class="field" style="margin-top:15px"><span>布局</span><select id="stitch-layout">${['横向','纵向','网格'].map(v=>`<option ${s.stitchLayout===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="field"><span>间距 · 像素</span><input id="gap" class="input" type="number" min="0" max="1024" step="1" value="${s.gap}"></label><label class="field"><span>背景</span><select id="background">${['白色','透明','指定颜色'].map(v=>`<option ${s.background===v?'selected':''}>${v}</option>`).join('')}</select></label>`;
    const output=s.output?`<section class="result-panel"><div class="row between"><div><h2>处理结果</h2><small>来源：${esc(s.output.inputName||image(s.output.inputId).name)} · ${operationName[s.output.operation]}</small></div>${pill(s.output.saved?'已存入永久图库':'临时结果',s.output.saved?'ok':'warn',s.output.saved?'check':'clock')}</div><div class="metric-pair"><div><small>处理前</small><strong>${s.output.inputSize||image(s.output.inputId).size}</strong><small>${s.output.inputWidth||image(s.output.inputId).width} × ${s.output.inputHeight||image(s.output.inputId).height} · ${s.output.inputFormat||image(s.output.inputId).format}</small></div>${icon('arrow')}<div><small>处理后 · 示例值</small><strong>${s.output.larger?'4.6 MB':'824 KB'}</strong><small>${s.output.width} × ${s.output.height} · ${s.output.format}</small></div></div>${s.output.larger?notice('结果体积比原图更大。可调整参数，或保留原图。','warn'):''}<p class="footer-note">${s.output.saved?'永久版本独立保留，临时清理不会删除它。':'临时保留至 10 月 4 日 14:40（24 小时）。保存到图库后独立保管。'}</p><div class="row" style="margin-top:16px">${btn(s.output.saved?'已保存':'保存到图库','save-output','primary','check',s.output.saved?'disabled':'')}${btn('导出','export','','download')}${btn('上传此结果','upload-output','','upload')}${btn('放弃临时结果','discard-output','quiet danger','trash',s.output.saved?'disabled':'')}</div></section>`:'';
    return `${pageTitle('图片处理',`${s.operation==='stitch'?`${s.stitchOrder.length} 张图片`:esc(p.name)} · 原图独立保留`,btn('选择图片','choose-input','secondary-action','image'))}${!p.available?notice('本机副本缺失。先重新关联相同内容，再开始处理。','warn'):''}<div class="editor-layout"><section class="editor-preview"><div class="editor-canvas">${photo(p)}${s.operation==='crop'?'<div class="cropbox"></div>':''}</div><div class="preview-caption">${icon('image')}<span>${s.operation==='stitch'?'拼接预览 · 排列示意':`${p.width} × ${p.height} · ${p.format}`}</span>${pill('原图')}</div>${s.operation==='stitch'?`<div class="row">${s.stitchOrder.map(id=>`<span style="width:58px">${photo(image(id))}</span>`).join('')}</div>`:''}</section><section class="editor-controls"><div class="tabs">${['compress','crop','stitch'].map(v=>`<button class="tab ${s.operation===v?'active':''}" data-action="operation" data-value="${v}">${operationName[v]}</button>`).join('')}</div>${controls}<label class="field"><span>输出格式</span><select id="format">${['WebP','JPEG','PNG'].map(v=>`<option ${s.format===v?'selected':''}>${v}</option>`).join('')}</select></label>${s.format!=='PNG'?`<label class="field"><span>编码质量 <strong id="quality-value">${s.quality}</strong></span><input id="quality" type="range" min="1" max="100" value="${s.quality}"><small>编码器参数，不代表保真百分比。WebP 此处使用有损编码。</small></label>`:'<p class="footer-note">PNG 不使用有损质量参数，可保留透明度。</p>'}${notice('生成新结果，不覆盖原图。','', 'shield')}${btn('生成处理结果','process','primary','editor',!p.available?'disabled':'')}</section></div>${output}<p class="footer-note">原型展示交互与参数校验，不执行真实编解码；预览与大小为示例。</p>`;
  }
  function tasksPage(){
    const all=s.tasks.flatMap(t=>t.items),c=counts(all);
    return `${pageTitle('上传任务','每张图片、每个目标，分别记录结果。',btn('新建上传','upload','primary','plus'))}<div class="filterbar"><div class="tabs"><button class="tab active">全部 ${s.tasks.length}</button></div><div class="row">${pill(`进行中 ${(c.running||0)+(c.waiting||0)}`,'accent')}${pill(`待确认 ${c.unknown||0}`,'warn')}</div></div>${s.scenario==='offline'?notice('当前离线。未开始的上传等待网络恢复，已确认链接仍保留。','warn'):''}<div class="task-layout"><section class="task-list">${s.tasks.map(t=>{
      const tc=counts(t.items),agg=aggregate(t),active=t.items.some(x=>['running','waiting'].includes(x.state));
      return `<article class="task-card"><div class="row between"><div class="task-title">${esc(t.name)} <small>${t.time} · ${t.items.length} 个发布项</small></div>${pill(agg,agg==='全部成功'?'ok':agg==='全部失败'?'bad':agg==='进行中'?'accent':'warn')}</div>${active?`<div class="progress" aria-label="当前传输示例进度"><div style="width:${t.items.find(x=>x.state==='running')?.progress||0}%"></div></div><div class="row between"><small>${t.paused?'停止新派发，在途请求可完成':tc.running?'正在执行 · 前台运行':'等待派发 · 尚未开始传输'}</small><small>${t.items.some(x=>x.state==='running')?'已知传输进度 62%':'未开始传输'}</small></div>`:`<p class="footer-note" style="margin-top:9px">成功 ${tc.succeeded||0} · 失败 ${tc.failed||0} · 待确认 ${tc.unknown||0} · 取消 ${tc.cancelled||0}</p>`}<div class="task-children">${t.items.map(x=>`<div class="task-child">${photo(image(x.asset))}<span class="child-name truncate" title="${esc(image(x.asset).name)}">${esc(image(x.asset).name)}</span><span class="target">${esc(x.target)}</span>${pill(t.paused&&x.state==='waiting'?'已暂停':stateText[x.state],stateKind[x.state])}</div>`).join('')}</div>${tc.failed?notice('ImgBB 授权失效。已成功的 Catbox 链接可继续使用。','bad','warning'):''}${tc.unknown?notice('远端可能已接收图片，但未取得确认。先核查结果；再次上传可能产生重复文件。','warn','warning'):''}<div class="row" style="margin-top:15px">${tc.succeeded?btn('复制成功链接','task-links','small','copy',`data-task="${t.id}"`):''}${tc.failed?btn('处理失败项','task-failed','small','refresh',`data-task="${t.id}"`):''}${tc.unknown?btn('核查 / 再次上传','unknown','small','info',`data-task="${t.id}"`):''}${active?btn(t.paused?'继续派发':'暂停派发','pause-task','small',t.paused?'play':'pause',`data-task="${t.id}"`)+btn('取消任务','cancel-task','small quiet danger','close',`data-task="${t.id}"`):''}${btn('诊断','diagnostic','small quiet','info')}</div></article>`;
    }).join('')}</section><aside class="task-summary"><h3>本次队列</h3><dl class="definition"><dt>发布项总数</dt><dd>${all.length}</dd><dt>成功</dt><dd>${c.succeeded||0}</dd><dt>失败</dt><dd>${c.failed||0}</dd><dt>待确认</dt><dd>${c.unknown||0}</dd><dt>进行中 / 等待</dt><dd>${(c.running||0)+(c.waiting||0)}</dd><dt>取消</dt><dd>${c.cancelled||0}</dd></dl><hr class="line"><div class="row">${icon('shield')}<h3>结果独立保留</h3></div><p class="footer-note">失败不影响其他目标。重试创建新的任务，历史结果保留。</p>${notice('移动端退到后台或锁屏后，任务可能中断。重开后核对状态。','', 'info')}</aside></div>`;
  }
  const accountData=()=>[{name:'Catbox',alias:'匿名目标',state:'无需凭据',kind:'ok',mark:'c',description:'选择图片后主动上传，成功后取得普通链接。',key:'不保存凭据',cap:'匿名上传 · 无应用内远端删除'}, {name:'Catbox',alias:'个人账号',state:'未验证',kind:'warn',mark:'c',description:'可配置 userhash，将后续上传关联到对应账号。',key:'尚未配置',cap:'账号上传 · 能力按服务资料确认'}, {name:'ImgBB',alias:'写作',state:s.accountState==='expired'?'授权失效':'已配置 · 未验证',kind:s.accountState==='expired'?'bad':'warn',mark:'ib',description:'使用 API Key 上传。更新凭据后可重新验证配置。',key:s.accountState==='expired'?'•••••••• · 需要更新':'•••••••• · 本次会话示例',cap:'API 上传 · 删除能力视返回信息'}, {name:'ImgBB',alias:'备用',state:'未配置',kind:'',mark:'ib',description:'同一图床可以保留多个账号，上传时单独选择目标。',key:'尚未配置',cap:'需要 API Key'}].map((a,i)=>s.accountOverrides[i]?{...a,...s.accountOverrides[i]}:a).concat(s.extraAccounts);
  function accountsPage(){return `${pageTitle('图床账号','服务账号用于上传；本地功能无需任何账号。',btn('添加账号','account','primary','plus'))}<div class="accounts-grid">${accountData().map((a,i)=>`<article class="account-card"><div class="row between"><div class="row"><span class="provider-mark">${a.mark}</span><div><h3>${a.name}</h3><small>${a.alias}</small></div></div>${pill(a.state,a.kind)}</div><p>${a.description}</p><dl class="definition"><dt>凭据</dt><dd>${a.key}</dd><dt>能力</dt><dd>${a.cap}</dd></dl><hr class="line"><div class="row">${btn(i===0?'上传到此目标':i===2&&s.accountState==='expired'?'更新凭据':'配置账号',i===0?'upload':'account','small',i===0?'upload':'settings',`data-account="${i}"`)}${i!==0?btn('配置说明','account-info','small quiet','info'):''}</div></article>`).join('')}</div><p class="footer-note">已配置不代表服务已验证可用。不同服务有自己的限制与保留政策；本应用不保证远程文件永久保留。<br>示例账号状态不来自实际接口，原型不接受或保存真实密钥。</p>`;}
  function settingsPage(){return `${pageTitle('设置','保管好图片，也保留你的选择。')}<div class="settings-layout"><section class="settings-group"><h2>使用偏好</h2><div class="setting-row"><div>界面主题<small>当前原型可切换深浅色</small></div>${btn(s.dark?'深色':'浅色','theme','small',s.dark?'moon':'sun')}</div><label class="setting-row"><div>上传网络<small>计费状态未知时先等待用户确认</small></div><select id="network">${[['unmetered','仅非计费网络'],['allow','允许计费网络']].map(([v,n])=>`<option value="${v}" ${s.draftPreferences.network===v?'selected':''}>${n}</option>`).join('')}</select></label><label class="setting-row"><div>临时结果保留<small>永久副本和活跃依赖受保护</small></div><select id="retention">${[['24','24 小时'],['1','1 小时'],['168','7 天']].map(([v,n])=>`<option value="${v}" ${s.draftPreferences.retention===v?'selected':''}>${n}</option>`).join('')}</select></label><div class="setting-row"><div>隐私元数据<small>上传副本默认移除位置与设备信息</small></div>${pill('默认去除','ok','shield')}</div><label class="setting-row"><div>上传并发<small>只影响尚未派发的任务</small></div><select id="concurrency">${[1,2,3,4].map(v=>`<option value="${v}" ${s.draftPreferences.concurrency===String(v)?'selected':''}>${v}</option>`).join('')}</select></label>${btn(s.settingSaved?'本次演示已保存':'保存设置','save-settings','primary small','check')}</section><section class="settings-group"><h2>存储空间</h2><div class="row between"><strong style="font-size:25px">33.9 MB</strong><small>示例占用</small></div><div class="space-track"><span></span><span></span><span></span><span></span></div><dl class="definition"><dt>永久图片</dt><dd>26.1 MB · 独立保管</dd><dt>回收区</dt><dd>3.2 MB · 可恢复</dd><dt>缩略图</dt><dd>${s.cacheCleaned?'0 MB':'2.1 MB'} · 可再生成</dd><dt>临时结果</dt><dd>2.4 MB · 1 项受任务保护</dd><dt>诊断日志</dt><dd>0.1 MB · 已脱敏</dd></dl><div class="row">${btn('清理可再生缓存','cleanup','small','trash')}${btn('回收区','page','small quiet','','data-page="recycle"')}</div></section><section class="settings-group"><h2>备份与恢复</h2><p class="muted" style="font-size:12px;margin-bottom:18px">完整备份包含永久图片；元数据备份只保留整理信息与普通链接。</p><div class="row">${btn('创建本地备份','backup','small','download')}${btn('恢复备份','restore','small','refresh')}</div><p class="footer-note">凭据、临时结果和待执行任务不进入备份。恢复后的账号需重新配置凭据。</p></section><section class="settings-group"><h2>诊断与数据</h2><div class="row">${btn('查看诊断','diagnostic','small','list')}${btn('导出脱敏诊断','diagnostic-export','small','download')}</div><p class="footer-note">诊断只保留必要的本机事件。不显示密钥或删除管理秘密。<br>卸载应用可能移除本机数据，建议提前完成备份。</p>${s.restored?notice(s.restoreMode==='replace'?'替换恢复演示完成：新图库预览含 5 项，恢复前快照保留。':'恢复演示完成：合并 3 项，复用 2 项；原有图片保留。','ok'):''}</section></div>`;}
  const morePage=()=>`${pageTitle('更多','账号、存储与备份，放在这里。')}<div class="more-grid">${btn('图床账号','page','','accounts','data-page="accounts"')}${btn('设置与存储','page','','settings','data-page="settings"')}${btn('回收区','page','','trash','data-page="recycle"')}${btn('创建备份','backup','','download')}${btn('恢复备份','restore','','refresh')}${btn('诊断','diagnostic','','list')}</div><p class="footer-note">本机图库无需登录。应用云同步属于后续版本。</p>`;
  function modalFrame(title,body,foot='',wide=false){return `<dialog id="modal" class="modal ${wide?'wide':''}" aria-labelledby="modal-title"><header class="modal-head"><h2 id="modal-title">${title}</h2>${btn('','close-modal','quiet square','close','aria-label="关闭对话框"')}</header><div class="modal-body">${body}</div>${foot?`<footer class="modal-foot">${foot}</footer>`:''}</dialog>`;}
  function modalHTML(){
    const m=s.modal,p=image(m.id||s.focus),set=m.ids?m.ids.map(image):selectedImages().length?selectedImages():[p];
    const cancel=btn('取消','close-modal','');
    if(m.type==='detail')return modalFrame('图片详情',`<div class="detail-grid"><div>${photo(p,'modal-photo')}</div><section><h3 style="overflow-wrap:anywhere">${esc(p.name)}</h3><dl class="definition"><dt>本机状态</dt><dd>${p.available?'永久副本可用':'副本缺失，整理信息保留'}</dd><dt>实际格式</dt><dd>${p.format} · ${p.size}</dd><dt>尺寸</dt><dd>${p.width} × ${p.height}</dd><dt>来源</dt><dd>系统选图 · 2026-10-03 14:18</dd><dt>分类</dt><dd>${esc(p.category)}</dd><dt>标签</dt><dd>${p.tags.map(esc).join('、')||'暂无'}</dd><dt>来源关系</dt><dd>${p.derived?'由原版本生成的新版本':'导入的原始版本'}</dd></dl><div class="row">${pill(p.favorite?'已收藏':'未收藏')}${btn(p.favorite?'取消收藏':'收藏','favorite','small','star',`data-id="${p.id}"`)}${btn('编辑整理','tags','small','tag',`data-id="${p.id}"`)}</div>${p.available?'':notice('重新导入相同内容可以修复；不同图片不会替代此版本。','warn')}<div class="result-line"><span>远程结果</span><span>${p.links.length} 个普通链接</span></div><div class="row">${btn('查看链接','links','small','link',`data-id="${p.id}" ${p.links.length?'':'disabled'}`)}${!p.available?btn('重新关联','repair','small','refresh',`data-id="${p.id}"`):''}${p.recycled?pill('回收区 · 先恢复再处理','warn'):btn('移到回收区','delete','small quiet danger','trash',`data-id="${p.id}"`)}</div></section></div>`,`${btn('关闭','close-modal')}${p.available&&!p.recycled?btn('处理图片','edit-image','primary','editor',`data-id="${p.id}"`):''}${btn('上传','upload','', 'upload',`data-id="${p.id}" ${p.available&&!p.recycled?'':'disabled'}`)}`,true);
    if(m.type==='import')return modalFrame('导入图片',`${notice('选择后复制到本机图库，外部原文件保持原样。','', 'shield')}<div class="stack"><label class="modal-row"><input type="radio" name="import-entry" checked><span>系统选图<small>可只授权你选择的图片，不要求完整图库访问。</small></span></label><label class="modal-row"><input type="radio" name="import-entry"><span>选择本机文件<small>首版支持 JPEG、PNG、WebP、GIF、BMP。</small></span></label></div><p class="dialog-hint">原型将演示 5 项：${s.images.some(x=>x.name==='海岸线 · 午后.jpg')?'3 项新图片、1 项重复':'4 项新图片'}、1 项获取失败。不会打开真实文件。</p>`,`${cancel}${btn('演示导入','import-run','primary','plus')}`);
    if(m.type==='import-result')return modalFrame('导入结果',`${notice(m.duplicate?'演示完成：3 项新图片、1 项重复复用、1 项获取失败。':'演示完成：4 项新图片、1 项获取失败。','ok','check')}<table class="result-table"><tr><td>窗边静物.jpg</td><td>${pill('已保管','ok')}</td></tr><tr><td>沙丘近景.jpg</td><td>${pill('已保管','ok')}</td></tr><tr><td>林间植物.png</td><td>${pill('已保管','ok')}</td></tr><tr><td>海岸线 · 午后.jpg</td><td>${pill(m.duplicate?'重复 · 整理保留':'已保管',m.duplicate?'':'ok')}</td></tr><tr><td>云端照片.jpg</td><td>${pill('未能获取','warn')}</td></tr></table><p class="dialog-hint">失败项未入库。可先在系统照片中下载原文件，再重新选择。</p>`,`${btn('稍后处理','close-modal')}${btn('重试获取失败项','import-retry','primary','refresh')}`);
    if(m.type==='import-retry')return modalFrame('重新取得照片',`${notice('原型中的云端资源仍未下载，未产生新副本。','warn')}<p>下载完成后重新选择该图片。已成功导入的其他图片不受影响。</p>`,btn('知道了','close-modal','primary'));
    if(m.type==='upload')return modalFrame('创建上传',`<div><h3>${set.length} 张图片 × 选定目标</h3><p class="dialog-hint" style="margin-top:5px">${set.map(x=>esc(x.name)).join('、')}</p></div><label class="field"><span>上传版本</span><select id="upload-version"><option>${m.output?'当前临时处理结果':'图库永久版本'}</option></select></label><label class="field"><span>图片策略</span><select id="upload-strategy"><option>生成隐私处理副本 · 去除敏感元数据</option><option>体积优先 · 新建处理副本</option><option>原样字节上传 · 可能保留隐私元数据</option></select></label><div class="stack">${accountData().map((a,i)=>`<label class="modal-row"><input data-upload-target="${i}" type="checkbox" ${(m.targets?m.targets.includes(i):i===0||i===2)?'checked':''}><span>${esc(a.name)} · ${esc(a.alias)}<small>${esc(a.state)}${i===0?'；保留期限以服务政策为准。':'；需要有效凭据后才可派发。'}</small></span></label>`).join('')}</div>${set.some(x=>!x.available)?notice('选择中包含缺失副本。先修复或移除该项，不会创建假上传。','bad'):''}<div id="upload-count" class="notice">${icon('info')}<span>预计创建 ${set.length*(m.targets?.length||2)} 个发布项；相同目标的成功结果默认复用。</span></div><p class="dialog-hint">这里只演示任务创建，不会把示例图片发送到图床。</p>`,`${cancel}${btn('创建上传任务','upload-confirm','primary','upload',set.some(x=>!x.available)?'disabled':'')}`);
    if(m.type==='filters')return modalFrame('筛选图库',`<label class="field"><span>分类</span><select id="category">${[['all','全部分类'],['旅行','旅行'],['素材','素材'],['日常','日常'],['未分类','未分类']].map(([v,n])=>`<option value="${v}" ${s.category===v?'selected':''}>${n}</option>`).join('')}</select></label><label class="field"><span>本机副本</span><select id="availability"><option value="all" ${s.availability==='all'?'selected':''}>全部状态</option><option value="available" ${s.availability==='available'?'selected':''}>本机可用</option><option value="missing" ${s.availability==='missing'?'selected':''}>副本缺失</option></select></label><small>与关键词、收藏及未上传筛选取交集；不会扩大已选图片范围。</small>`,`${btn('清除筛选','clear-filter')}${btn('应用筛选','apply-filters','primary','filter')}`);
    if(m.type==='tags')return modalFrame(`整理 ${set.length} 张图片`,`<label class="field"><span>分类</span><select id="edit-category">${(set.length>1?['保持原分类','旅行','素材','日常','未分类']:['旅行','素材','日常','未分类']).map(n=>`<option ${(m.draftCategory||(set.length>1?'保持原分类':set[0].category))===n?'selected':''}>${n}</option>`).join('')}</select></label><label class="field"><span>${set.length===1?'标签（逗号分隔）':'追加标签（逗号分隔）'}</span><input id="edit-tags" class="input" value="${esc(m.draftTags??(set.length===1?set[0].tags.join(', '):''))}" placeholder="例如：海岸, 夏日"><small>单个标签 1–64 个 Unicode 字符，最多 50 个。批量追加保留已有标签。</small></label>${m.error?`<p class="error-text" role="alert">${esc(m.error)}</p>`:''}`,`${cancel}${btn('保存整理','tags-confirm','primary','check')}`);
    if(m.type==='delete')return modalFrame('移到本地回收区',`${notice(`将移除 ${set.length} 张图片，可在回收区恢复。`,'warn','trash')}<p>保留本机副本、标签和已有链接。不会删除外部原文件，也不会调用图床删除。</p>`,`${cancel}${btn('移到回收区','delete-confirm','danger','trash')}`);
    if(m.type==='cleanup')return modalFrame('清理可再生缓存',`<p>演示可清理缩略图缓存 ${s.cacheCleaned?'0':'2.1'} MB。之后浏览时可重新生成。</p>${notice('永久图片、回收区副本和活跃任务依赖不在清理范围。','', 'shield')}<p class="dialog-hint">临时结果按到期时间与保护引用分别检查，不在此按钮中一并删除。</p>`,`${cancel}${btn('清理缓存','cleanup-confirm','primary','trash')}`);
    if(m.type==='links'){
      const linked=set.filter(x=>m.results?m.results.some(r=>r.id===x.id):x.links.length); const fmt=m.format||'URL';const values=linked.flatMap(x=>(m.results?m.results.filter(r=>r.id===x.id).map(r=>r.target):x.links).map(t=>{const u=`https://example.invalid/${t.toLowerCase()}/sample-${x.id}.${x.format.toLowerCase()==='jpeg'?'jpg':x.format.toLowerCase()}`;return fmt==='Markdown'?`![${x.name.replace(/[\\\[\]]/g,'\\$&')}](${u})`:fmt==='HTML'?`<img src="${u}" alt="${x.name.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}">`:fmt==='BBCode'?`[img]${u}[/img]`:u;}));
      return modalFrame('普通图片链接',`<div class="tabs">${['URL','Markdown','HTML','BBCode'].map(v=>`<button class="tab ${fmt===v?'active':''}" data-action="link-format" data-value="${v}">${v}</button>`).join('')}</div><div class="link-box">${esc([...new Set(values)].join('\n')||'没有可用普通链接')}</div><p class="dialog-hint">${values.length} 个示例链接 · 跳过 ${set.length-linked.length} 张无链接图片。顺序按图片及目标排列。<br>example.invalid 为演示地址，不是真实图床结果；有链接不代表已确认可访问。</p>`,`${btn('关闭','close-modal')}${btn('演示复制链接','copy-links','primary','copy',values.length?'':'disabled')}`);
    }
    if(m.type==='unknown')return modalFrame('上传结果待确认',`${notice('服务可能已接收图片，当前没有确认依据。','warn')}<p>可以先到对应图床检查。再次上传会创建新任务，可能产生另一个远端文件；旧的待确认记录仍保留。</p><label class="modal-row"><input id="duplicate-confirm" type="checkbox"><span>我理解再次上传可能产生重复文件</span></label>`,`${btn('稍后核查','close-modal')}${btn('明确再次上传','unknown-confirm','primary','upload','disabled')}`);
    if(m.type==='task-failed')return modalFrame('处理授权失败项',`${notice('先更新 ImgBB 凭据。已成功的其他目标不重复上传。','bad')}<p>当前失败项保留历史；确认后新建一个任务，等待有效授权。</p>`,`${btn('更新账号','page','','accounts','data-page="accounts"')}${btn('新建失败项重试','retry-failed','primary','refresh')}`);
    if(m.type==='cancel-task')return modalFrame('取消未完成项',`${notice('停止新派发并尝试停止当前执行。','warn')}<p>已经发生的远端上传可能无法撤回。确认后的远端结果会独立保留；取消不立即解除正在使用的文件保护。</p>`,`${cancel}${btn('取消未完成项','cancel-task-confirm','danger','close')}`);
    if(m.type==='account')return modalFrame('配置图床账号',`<label class="field"><span>图床</span><select id="account-provider" ${m.account==='new'?'':'disabled'}>${['Catbox','ImgBB'].map(n=>`<option ${(m.account==='new'?'Catbox':accountData()[m.account].name)===n?'selected':''}>${n}</option>`).join('')}</select></label><label class="field"><span>账号名称</span><input id="account-name" class="input" value="${m.account==='new'?'新账号':esc(accountData()[m.account].alias)}"></label><label class="field"><span>凭据</span><input id="account-key" class="input" value="示例凭据 · 不输入真实密钥" readonly><small>此原型只接受演示配置，不读取或保存真实密钥。</small></label><label class="modal-row"><input id="account-session" type="checkbox" checked><span>本次会话使用<small>真实应用安全存储失败时，不能退回明文保存。</small></span></label>`,`${cancel}${btn('保存示例配置','account-confirm','primary','check')}`);
    if(m.type==='account-info')return modalFrame('账号与能力',`<p>配置验证与上传授权分开。未知的服务能力先说明限制，不用隐藏测试上传验证密钥。</p>${notice('原型没有调用服务接口，示例状态不能作为服务健康证明。')}<p class="dialog-hint">停用账号只影响后续派发；移除账号不会清空已有远程链接。首版仅 Catbox 与 ImgBB。</p>`,btn('知道了','close-modal','primary'));
    if(m.type==='choose-input')return modalFrame('选择处理图片',`<label class="field"><span>本机图库</span><select id="editor-input">${s.images.filter(p=>!p.recycled).map(p=>`<option value="${p.id}" ${s.focus===p.id?'selected':''}>${esc(p.name)}${p.available?'':'（副本缺失）'}</option>`).join('')}</select></label><p class="dialog-hint">裁剪逐张确认；拼接按一组确认；批量压缩从图库多选进入。</p>`,`${cancel}${btn('使用这张','choose-confirm','primary','image')}`);
    if(m.type==='process-error')return modalFrame(s.scenario==='budget'?'处理前资源检查':'处理未完成',`${notice(s.scenario==='budget'?'预计像素与中间结果超过可用预算，尚未分配画布。':'当前示例输出生成失败，原图保持完整。','bad')}<p>${s.scenario==='budget'?'降低输出尺寸、减少拼接图片，或取消处理。':'可修改参数后重新生成，不会把失败文件显示成有效结果。'}</p>`,`${cancel}${btn('降低尺寸并返回','lower-size','primary','editor')}`);
    if(m.type==='export')return modalFrame('导出处理结果',`${notice('导出到系统允许的位置，应用内副本继续保留。','', 'download')}<label class="field"><span>文件名</span><input id="export-name" class="input" value="${esc(s.output?.name||'图片导出.webp')}"></label><label class="field"><span>同名文件处理</span><select><option>生成新名称（默认）</option><option>逐项询问是否覆盖</option></select></label><p class="dialog-hint">桌面可选文件位置；手机通过系统文件入口或照片保存入口。系统分享不等同于保存成功。</p>`,`${cancel}${btn('演示导出','export-confirm','primary','download')}`);
    if(m.type==='export-result')return modalFrame('导出结果',`${notice(m.denied?'系统未允许写入，未导出任何文件。':'演示：1 项导出成功，应用内结果仍保留。',m.denied?'warn':'ok')}<p>${m.denied?'可以重新选择允许的位置，或到系统设置检查该功能所需权限。':'实际应用只有系统确认写入后才报告成功。此原型没有创建真实图片文件。'}</p>`,`${btn('返回','close-modal')}${m.denied?btn('重新选择位置','export','primary','download'):''}`);
    if(m.type==='backup')return modalFrame('创建本地备份',`<label class="modal-row"><input type="radio" name="backup-type" value="full" ${s.backupType==='full'?'checked':''}><span>完整备份<small>永久图片 + 整理信息 + 普通远程链接。</small></span></label><label class="modal-row"><input type="radio" name="backup-type" value="metadata" ${s.backupType==='metadata'?'checked':''}><span>元数据备份<small>不含原图，不能单独恢复图片内容。</small></span></label>${notice('不包含凭据、删除管理秘密、临时结果和待执行任务。','', 'shield')}<p class="dialog-hint">在本机选择保存位置。备份不自动上传云端。</p>`,`${cancel}${btn('演示创建备份','backup-confirm','primary','download')}`);
    if(m.type==='backup-result')return modalFrame(m.missing?'完整备份尚未完成':'备份结果',`${notice(m.missing?'发现 1 个必要副本缺失，不能报告完整备份成功。':`演示：${s.backupType==='full'?'完整':'元数据'}备份已完成。`,m.missing?'warn':'ok')}<p>${m.missing?'先修复山间湖泊.webp，或改为元数据备份；取消不会破坏现有数据。':'实际备份需要完整性清单与校验。原型只展示结果，不生成可恢复备份文件。'}</p>`,`${btn('关闭','close-modal')}${m.missing?btn('改为元数据备份','metadata-backup','primary'):''}`);
    if(m.type==='restore')return modalFrame('恢复本地备份',`<p>示例备份：imagehost_2026-10-02.zip</p><label class="field"><span>恢复方式</span><select id="restore-mode"><option value="merge">合并（默认保留现有数据）</option><option value="replace">替换（需要再次确认）</option></select></label>${notice('先校验清单、图片与可用空间，再提交恢复。账号凭据需要重新配置。','', 'shield')}<label class="modal-row"><input id="restore-corrupt" type="checkbox"><span>演示损坏备份</span></label><p class="dialog-hint">恢复旧任务历史不会自动重新执行上传。</p>`,`${cancel}${btn('校验并预览','restore-check','primary','refresh')}`);
    if(m.type==='restore-preview')return modalFrame(m.corrupt?'备份校验失败':'恢复预览',`${notice(m.corrupt?'完整性校验不通过，现有数据未被覆盖。':`预计合并 3 项、复用 2 项，图片副本已通过示例校验。`,m.corrupt?'bad':'ok')}${!m.corrupt?`<p>${m.replace?'你选择了替换。提交前保留可恢复快照。':'合并不会删除已有图片与整理信息。'}</p>${m.replace?'<label class="modal-row"><input id="replace-confirm" type="checkbox"><span>确认替换当前图库，并保留恢复前快照</span></label>':''}`:''}<p class="dialog-hint">校验结果为模拟数据，不证明真实备份格式与恢复代码已实现。</p>`,`${btn('返回选择','restore')}${!m.corrupt?btn('确认恢复演示','restore-confirm','primary','check',m.replace?'disabled':''):''}`);
    if(m.type==='diagnostic')return modalFrame('脱敏诊断',`<div class="link-box">14:32:08  UPLOAD_AUTH_REQUIRED\n目标：ImgBB · 写作\n任务：文章配图 / 第 2 项\n凭据：[已脱敏]\n建议：更新账号凭据后新建重试任务。\n\n14:26:40  REMOTE_RESULT_UNKNOWN\n目标：Catbox · 匿名\n提交后连接中断；未自动重试。</div><p class="dialog-hint">仅示例事件。原图路径、账号秘密与删除管理链接不进入导出内容。</p>`,`${btn('关闭','close-modal')}${btn('演示导出诊断','diagnostic-export','primary','download')}`);
    if(m.type==='guard')return modalFrame(m.title||'操作未完成',`${notice(esc(m.message),'warn')}<p class="dialog-hint">已有有效图片、整理信息与链接保留。</p>`,btn('返回','close-modal','primary'));
    return '';
  }
  function render(){
    const active=document.activeElement;const activeId=active?.id;const start=active?.selectionStart,end=active?.selectionEnd;
    document.body.classList.toggle('dark',s.dark);
    const views={library:libraryPage,recycle:libraryPage,editor:editorPage,tasks:tasksPage,accounts:accountsPage,settings:settingsPage,more:morePage};
    root.innerHTML=shell((views[s.page]||libraryPage)());
    if(s.modal){const d=document.getElementById('modal');d.showModal();d.addEventListener('cancel',e=>{e.preventDefault();s.modal=null;render();});}
    if(activeId){const el=document.getElementById(activeId);if(el){el.focus({preventScroll:true});if(typeof start==='number'&&el.setSelectionRange){try{el.setSelectionRange(start,end);}catch{}}}}
    document.title=`ImageHost · ${scheme.toUpperCase()} ${schemeNames[scheme]} · ${pageNames[s.page]}`;
  }
  function toast(message){s.toast=message;clearTimeout(toastTimer);render();toastTimer=setTimeout(()=>{s.toast='';render();},4300);}
  function open(type,extra={}){s.modal={type,...extra};render();}
  function toPage(page){if(page==='recycle'||s.page==='recycle'){s.selected.clear();if(page!=='recycle')s.focus=s.images.find(x=>!x.recycled)?.id||0;}s.page=page;s.modal=null;render();window.scrollTo({top:0,behavior:'instant'});}
  function scenario(value){
    s.scenario=value;s.modal=null;s.output=null;s.images=fixtures();s.tasks=tasksFixture();s.selected.clear();s.focus=1;
    if(value==='empty'){s.images=[];s.tasks=[];}
    if(value==='missing')s.images[3].available=false;
    if(['empty','loading','load-error','missing','low-space'].includes(value))s.page='library';
    if(['offline','unknown'].includes(value)){s.page='tasks';if(value==='offline')s.tasks[2].items=s.tasks[2].items.map(x=>({...x,state:'waiting',reason:'等待网络恢复'}));}
    if(['process-error','budget','save-error','permission','larger'].includes(value)){s.page='editor';if(['save-error','permission','larger'].includes(value))s.output={saved:false,larger:value==='larger',inputId:1,format:'WebP',width:1600,height:1067,operation:'compress',quality:85,longest:1600,size:value==='larger'?'4.6 MB':'824 KB',name:'海岸线_处理结果.webp',ids:[1]};}
    render();
  }
  const handlers={
    'page':el=>toPage(el.dataset.page), 'close-modal':()=>{s.modal=null;render();},
    theme:()=>{s.dark=!s.dark;render();},
    reset:()=>{location.href=location.pathname;}, 'resolve-scenario':()=>scenario('normal'),
    detail:el=>{s.focus=Number(el.dataset.id);open('detail',{id:s.focus});},
    'filter':el=>{s.filter=el.dataset.value;render();}, favorites:()=>{s.filter='favorites';toPage('library');},category:el=>{s.category=el.dataset.value;toPage('library');},
    'clear-filter':()=>{s.query='';s.filter='all';s.category='all';s.availability='all';s.modal=null;render();},
    'filters':()=>open('filters'), 'apply-filters':()=>{s.category=document.getElementById('category').value;s.availability=document.getElementById('availability').value;s.modal=null;render();},
    'grid':()=>{s.view='grid';render();}, 'list':()=>{s.view='list';render();},
    'select-all':()=>{const f=filtered();const all=f.length&&f.every(p=>s.selected.has(p.id));f.forEach(p=>all?s.selected.delete(p.id):s.selected.add(p.id));render();},
    'clear-selection':()=>{s.selected.clear();render();},
    favorite:el=>{const p=image(Number(el.dataset.id));p.favorite=!p.favorite;render();},
    tags:el=>open('tags',{id:el.dataset.id?Number(el.dataset.id):undefined,ids:el.dataset.id?[Number(el.dataset.id)]:undefined}),
    'tags-confirm':()=>{const field=document.getElementById('edit-tags').value;s.modal.draftTags=field;s.modal.draftCategory=document.getElementById('edit-category').value;const tags=field.split(/[,，]/).map(x=>x.trim().normalize('NFC')).filter(Boolean);const set=s.modal.ids?s.modal.ids.map(image):selectedImages().length?selectedImages():[image(s.modal.id||s.focus)];const norm=new Map();tags.forEach(t=>{if(!norm.has(t.toLocaleLowerCase()))norm.set(t.toLocaleLowerCase(),t);});const clean=[...norm.values()];if(clean.some(t=>[...t].length>64)||clean.length>50||set.length>1&&set.some(p=>new Set([...p.tags,...clean].map(t=>t.toLocaleLowerCase())).size>50)){s.modal.error='标签最多 50 个，每个 1–64 个字符。现有整理未改变。';render();return;}const category=document.getElementById('edit-category').value;set.forEach(p=>{if(category!=='保持原分类')p.category=category;p.tags=set.length===1?clean:[...new Map([...p.tags,...clean].map(t=>[t.toLocaleLowerCase(),t])).values()];});s.modal=null;toast(`演示：已更新 ${set.length} 张图片的整理信息。`);},
    import:()=>s.scenario==='low-space'?open('guard',{title:'暂停新导入',message:'空间不足。先管理存储空间，再创建新副本。'}):open('import'),
    'import-run':()=>{const duplicate=s.images.some(x=>x.name==='海岸线 · 午后.jpg');const next=Math.max(9,...s.images.map(p=>p.id))+1;[['窗边静物.jpg',2],['沙丘近景.jpg',7],['林间植物.png',8]].forEach(([name,sprite],i)=>s.images.push({...fixtures()[sprite],id:next+i,name,links:[],partial:false,tags:[],category:'未分类',favorite:false}));if(!duplicate)s.images.push({...fixtures()[0],id:next+3,links:[],partial:false,tags:[],category:'未分类',favorite:false});if(!s.images.some(x=>x.id===s.focus&&!x.recycled))s.focus=s.images.find(x=>!x.recycled)?.id||0;s.scenario='normal';open('import-result',{duplicate});},
    'import-retry':()=>open('import-retry'),
    'edit-image':el=>{s.focus=Number(el.dataset.id)||s.focus;s.output=null;toPage('editor');},
    'process-selected':()=>{const set=selectedImages();if(set.some(p=>!p.available)){open('guard',{message:'选中内容包含缺失副本，先修复或从选择中移除。'});return;}s.focus=set[0]?.id||s.focus;s.stitchOrder=set.length>=2?set.map(p=>p.id):[s.focus,...s.images.filter(x=>x.id!==s.focus&&!x.recycled&&x.available).slice(0,1).map(x=>x.id)];s.output=null;toPage('editor');},
    'choose-input':()=>open('choose-input'), 'choose-confirm':()=>{s.focus=Number(document.getElementById('editor-input').value);s.stitchOrder=[s.focus,...s.images.filter(x=>x.id!==s.focus&&!x.recycled&&x.available).slice(0,1).map(x=>x.id)];s.output=null;s.modal=null;render();},
    operation:el=>{s.operation=el.dataset.value;if(s.operation==='stitch'&&!s.stitchOrder.includes(s.focus))s.stitchOrder=[s.focus,...s.images.filter(x=>x.id!==s.focus&&!x.recycled&&x.available).slice(0,1).map(x=>x.id)];s.output=null;render();},
    'stitch-left':el=>{const i=Number(el.dataset.index);if(i>0)[s.stitchOrder[i-1],s.stitchOrder[i]]=[s.stitchOrder[i],s.stitchOrder[i-1]];render();},
    'stitch-right':el=>{const i=Number(el.dataset.index);if(i<s.stitchOrder.length-1)[s.stitchOrder[i],s.stitchOrder[i+1]]=[s.stitchOrder[i+1],s.stitchOrder[i]];render();},
    process:()=>{if(!s.images.some(x=>x.id===s.focus&&!x.recycled&&x.available)){open('guard',{message:'没有有效本机输入，尚未开始处理。'});return;}if(s.operation==='stitch'&&(s.stitchOrder.length<2||s.stitchOrder.some(id=>!s.images.some(x=>x.id===id&&!x.recycled&&x.available)))){open('guard',{message:'拼接需要至少两张有效本机图片，尚未开始处理。'});return;}const size=Number(document.getElementById('longest')?.value??s.longest),gap=Number(document.getElementById('gap')?.value??s.gap);if(s.operation==='compress'&&s.policy==='size'&&(!Number.isInteger(size)||size<1||size>16384)){open('guard',{message:'最长边需要是 1–16384 的整数像素，不能静默修正。'});return;}if(s.operation==='stitch'&&(!Number.isInteger(gap)||gap<0||gap>1024)){open('guard',{message:'拼接间距需要是 0–1024 的整数像素。'});return;}if(s.operation==='crop'){const values=['crop-x','crop-y','crop-w','crop-h'].map(id=>Number(document.getElementById(id).value));const [x,y,w,h]=values,p=image(s.focus);if(values.some(v=>!Number.isInteger(v))||x<0||y<0||w<1||h<1||x+w>p.width||y+h>p.height){open('guard',{message:'裁剪区域需要为图内有效整数像素，不能越界。'});return;}}if(['process-error','budget','low-space'].includes(s.scenario)){open('process-error');return;}s.output=createOutput();toast('演示：生成了新的临时结果，原图保持完整。');},
    'lower-size':()=>{s.longest=1200;s.scenario='normal';s.modal=null;render();},
    'save-output':()=>{if(s.scenario==='save-error'){open('guard',{title:'保存到图库失败',message:'永久副本提交失败。临时结果保留，未显示为已保存。'});return;}if(!s.output||s.output.saved)return;const p=s.images.find(x=>x.id===s.output.inputId&&!x.recycled);if(!p){open('guard',{message:'来源版本不可用，尚未永久保存。'});return;}const id=Math.max(0,...s.images.map(x=>x.id))+1;s.images.push({...p,id,name:s.output.name,format:s.output.format,size:s.output.size,width:s.output.width,height:s.output.height,links:[],partial:false,derived:true,tags:[...p.tags],available:true});s.output.saved=true;toast('演示：新版本已保存到永久图库，保留来源关系。');},
    'discard-output':()=>{s.output=null;toast('演示：已放弃未保存的临时结果，原图保留。');},
    export:()=>open('export'), 'export-confirm':()=>open('export-result',{denied:s.scenario==='permission'}),
    upload:el=>{const ids=el.dataset.id?[Number(el.dataset.id)]:selectedImages().map(p=>p.id);const chosen=ids.length?ids:[s.focus];if(chosen.some(id=>!s.images.some(p=>p.id===id&&!p.recycled))){open('guard',{message:'请先从有效图库选择图片，回收区内容不能直接上传。'});return;}open('upload',{ids:chosen,targets:el.dataset.account===undefined?undefined:[Number(el.dataset.account)]});}, 'upload-output':()=>open('upload',{ids:[s.output.inputId],output:true}),
    'upload-confirm':()=>{const chosen=[...document.querySelectorAll('[data-upload-target]:checked')].map(el=>Number(el.dataset.uploadTarget));if(!chosen.length){open('guard',{message:'至少选择一个上传目标。尚未创建任务。'});return;}const m=s.modal,ids=m.ids||[s.focus],strategy=document.getElementById('upload-strategy').value,accounts=accountData();const items=ids.flatMap(id=>chosen.map(index=>{const a=accounts[index],reuse=!m.output&&strategy==='生成隐私处理副本 · 去除敏感元数据'&&((index===0&&image(id).links.includes('Catbox'))||(index===2&&image(id).links.includes('ImgBB')));return {asset:id,target:a.name+' · '+a.alias,account:index,state:reuse?'succeeded':'waiting',reason:index>0&&a.state!=='已配置 · 未验证'?'等待配置有效凭据':s.scenario==='offline'?'等待网络恢复':'等待派发',strategy,version:m.output?{...s.output}:null};}));s.tasks.unshift({id:'new-'+Date.now(),name:m.output?'处理结果发布':'新建图片上传',time:'本次演示',paused:false,items});toPage('tasks');toast(`演示：${items.length} 个发布项已记录，版本、目标与策略已固定。`);},
    links:el=>open('links',{ids:el.dataset.id?[Number(el.dataset.id)]:selectedImages().map(p=>p.id)}),
    'task-links':el=>{const t=s.tasks.find(x=>x.id===el.dataset.task);const successful=t.items.filter(x=>x.state==='succeeded');open('links',{ids:[...new Set(successful.map(x=>x.asset))],results:successful.map(x=>({id:x.asset,target:x.target.startsWith('Catbox')?'Catbox':'ImgBB'}))});},
    'link-format':el=>{s.modal.format=el.dataset.value;render();}, 'copy-links':()=>{s.modal=null;toast('演示：显示复制成功反馈；未改动系统剪贴板，也未重新上传。');},
    unknown:el=>open('unknown',{task:el.dataset.task}), 'unknown-confirm':()=>{const old=s.tasks.find(t=>t.id===s.modal.task);const items=old.items.filter(x=>x.state==='unknown').map(x=>({...x,state:'waiting',reason:'用户明确再次上传'}));s.tasks.unshift({id:'retry-'+Date.now(),name:'明确再次上传',time:'本次演示',paused:false,items});s.modal=null;toast('演示：已新建任务，旧的待确认记录保留。');},
    'task-failed':el=>open('task-failed',{task:el.dataset.task}), 'retry-failed':()=>{const old=s.tasks.find(t=>t.id===s.modal.task);s.tasks.unshift({id:'failed-'+Date.now(),name:'失败项重试',time:'本次演示',paused:false,items:old.items.filter(x=>x.state==='failed').map(x=>({...x,state:'waiting',reason:'等待有效授权'}))});s.modal=null;toast('演示：仅失败项新建重试任务，成功项保留。');},
    'pause-task':el=>{const t=s.tasks.find(x=>x.id===el.dataset.task);t.paused=!t.paused;toast(t.paused?'演示：停止新派发，在途请求仍可完成。':'演示：恢复派发；不承诺断点续传。');},
    'cancel-task':el=>open('cancel-task',{task:el.dataset.task}), 'cancel-task-confirm':()=>{const t=s.tasks.find(x=>x.id===s.modal.task);t.items.forEach(x=>{if(['running','waiting'].includes(x.state))x.state='cancelled';});s.modal=null;toast('演示：已取消未完成项，已确认结果独立保留。');},
    account:el=>open('account',{account:el.dataset.account===undefined?'new':Number(el.dataset.account)}), 'account-confirm':()=>{const i=s.modal.account,name=document.getElementById('account-provider').value,alias=document.getElementById('account-name').value.trim();if(!alias){toast('请填写账号名称，配置未提交。');return;}const update={name,alias,state:'已配置 · 未验证',kind:'warn',key:'•••••••• · 本次会话示例'};if(i==='new')s.extraAccounts.push({...update,mark:name==='Catbox'?'c':'ib',description:'新建的演示账号，可独立作为后续上传目标。',cap:name==='Catbox'?'账号上传 · 需 userhash':'API 上传 · 需 API Key'});else if(i>=4)s.extraAccounts[i-4]={...s.extraAccounts[i-4],...update};else{s.accountOverrides[i]=update;if(i===2)s.accountState='configured';}s.modal=null;toast('演示：对应账号配置已记录，尚未验证服务可用性。');}, 'account-info':()=>open('account-info'),
    repair:()=>open('guard',{title:'重新关联本机副本',message:'真实应用需重新选择并核对相同内容。此原型不读取文件，不会将不同图片当作原版本。'}),
    delete:el=>open('delete',{ids:el.dataset.id?[Number(el.dataset.id)]:selectedImages().map(p=>p.id)}),
    'delete-confirm':()=>{const ids=s.modal.ids?.length?s.modal.ids:[s.focus];ids.forEach(id=>{image(id).recycled=true;});s.selected.clear();s.modal=null;toast(`演示：${ids.length} 张图片已移到回收区，可恢复。`);},
    'restore-images':()=>{selectedImages().forEach(p=>p.recycled=false);s.selected.clear();toast('演示：已恢复图片及整理信息，身份和链接保留。');},
    cleanup:()=>open('cleanup'), 'cleanup-confirm':()=>{s.cacheCleaned=true;s.modal=null;toast('演示：缩略图缓存已清理，永久图片与活跃依赖保留。');},
    'save-settings':()=>{if(s.scenario==='save-error'){open('guard',{message:'设置保存失败，现有有效设置继续使用。'});return;}s.preferences={...s.draftPreferences};s.settingSaved=true;toast('演示：设置已保存，仅保留到本次页面刷新。');},
    backup:()=>open('backup'), 'backup-confirm':()=>open('backup-result',{missing:s.backupType==='full'&&s.images.some(p=>!p.available)}), 'metadata-backup':()=>{s.backupType='metadata';open('backup-result');},
    restore:()=>open('restore'), 'restore-check':()=>open('restore-preview',{corrupt:document.getElementById('restore-corrupt').checked,replace:document.getElementById('restore-mode').value==='replace'}),
    'restore-confirm':()=>{s.restoreMode=s.modal.replace?'replace':'merge';s.restored=true;s.modal=null;toPage('settings');toast('演示：'+(s.restoreMode==='replace'?'替换':'合并')+'恢复汇总已更新，未读写真实图库或备份。');},
    diagnostic:()=>open('diagnostic'), 'diagnostic-export':()=>{s.modal=null;toast('演示：脱敏诊断导出反馈。未生成真实日志文件。');}
  };
  document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled){handlers[el.dataset.action]?.(el);}});
  document.addEventListener('change',e=>{
    const el=e.target;
    if(el.dataset.select){const id=Number(el.dataset.select);el.checked?s.selected.add(id):s.selected.delete(id);s.focus=id;render();return;}
    const changes={network:()=>{s.draftPreferences.network=el.value;s.settingSaved=false;render();},retention:()=>{s.draftPreferences.retention=el.value;s.settingSaved=false;render();},concurrency:()=>{s.draftPreferences.concurrency=el.value;s.settingSaved=false;render();},'crop-x':()=>{s.crop.x=el.value;},'crop-y':()=>{s.crop.y=el.value;},'crop-w':()=>{s.crop.w=el.value;},'crop-h':()=>{s.crop.h=el.value;},'stitch-layout':()=>{s.stitchLayout=el.value;},background:()=>{s.background=el.value;},scenario:()=>scenario(el.value),sort:()=>{s.sort=el.value;render();},policy:()=>{s.policy=el.value;render();},format:()=>{s.format=el.value;render();},ratio:()=>{s.ratio=el.value;render();},longest:()=>{s.longest=Number(el.value);},gap:()=>{s.gap=Number(el.value);},'duplicate-confirm':()=>{document.querySelector('[data-action="unknown-confirm"]').disabled=!el.checked;},'replace-confirm':()=>{document.querySelector('[data-action="restore-confirm"]').disabled=!el.checked;}};
    changes[el.id]?.();if(el.name==='backup-type')s.backupType=el.value;
    if(el.dataset.uploadTarget!==undefined){const count=document.querySelectorAll('[data-upload-target]:checked').length*(s.modal.ids?.length||1);document.getElementById('upload-count').innerHTML=icon('info')+`<span>预计创建 ${count} 个发布项；相同目标的成功结果默认复用。</span>`;}
  });
  document.addEventListener('input',e=>{const el=e.target;if(['crop-x','crop-y','crop-w','crop-h'].includes(el.id))s.crop[el.id.slice(5)]=el.value;if(el.id==='longest')s.longest=Number(el.value);if(el.id==='gap')s.gap=Number(el.value);if(el.id==='edit-tags'&&s.modal)s.modal.draftTags=el.value;if(e.target.dataset.input==='query'){s.query=e.target.value;render();}if(e.target.id==='quality'){s.quality=Number(e.target.value);document.getElementById('quality-value').textContent=s.quality;}});
  document.addEventListener('keydown',e=>{const inField=e.target.matches('input,textarea,select');if(e.key==='/'&&!inField&&!s.modal){e.preventDefault();const inputs=[...document.querySelectorAll('[data-input="query"]')];inputs.find(x=>x.getBoundingClientRect().width>0)?.focus();}if(e.key==='Escape'&&!s.modal&&s.selected.size){s.selected.clear();render();}});
  if(s.scenario!=='normal')scenario(s.scenario);else render();
})();
