/* Interaction prototype only: synthetic images, volatile state, no real imports or uploads. */
(() => {
  'use strict';
  const q = new URLSearchParams(location.search), mode=q.get('mode')==='m2'?'m2':'m1';
  const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const paths={image:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 6-6 4 4 3-3 5 5"/>',plus:'<path d="M12 5v14M5 12h14"/>',back:'<path d="m14 5-7 7 7 7"/>',next:'<path d="m9 5 7 7-7 7"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',link:'<path d="m9 15 6-6M8 16l-2 2a4 4 0 0 1-5-5l4-4a4 4 0 0 1 5 0m4-1 2-2a4 4 0 0 1 5 5l-4 4a4 4 0 0 1-5 0"/>',upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 15v5h16v-5"/>',edit:'<path d="m4 16 11-11 4 4-11 11H4zm10-10 4 4"/>',crop:'<path d="M6 2v16h16M2 6h16v16"/>',stitch:'<rect x="3" y="4" width="8" height="16" rx="2"/><rect x="13" y="4" width="8" height="16" rx="2"/>',compress:'<path d="M8 3v5H3m18 0h-5V3M3 16h5v5m8 0v-5h5"/>',check:'<path d="m5 12 4 4L19 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',settings:'<path d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z"/><path d="m10 3-1 3-3 1-3 3 2 2-2 2 3 3 3 1 1 3h4l1-3 3-1 3-3-2-2 2-2-3-3-3-1-1-3Z"/>',folder:'<path d="M3 7V4h7l2 3h9v13H3Z"/>',cloud:'<path d="M7 18H5a4 4 0 0 1-1-8 7 7 0 0 1 13-2 5 5 0 0 1 2 10h-2M12 12v9m-3-3 3 3 3-3"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',star:'<path d="m12 3 3 6 6 1-4 5 1 6-6-3-6 3 1-6-4-5 6-1Z"/>',pause:'<path d="M8 5v14M16 5v14"/>',trash:'<path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7"/>',history:'<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7m2-5v6l4 2"/>'};
  const ico=n=>`<svg viewBox="0 0 24 24" aria-hidden="true">${paths[n]||paths.info}</svg>`;
  const btn=(t,a,cl='',icon='',attrs='')=>`<button type="button" class="button ${cl}" data-action="${a}" ${attrs}>${icon?ico(icon):''}${esc(t)}</button>`;
  const ib=(label,a,icon,cl='')=>`<button type="button" class="iconbtn ${cl}" aria-label="${label}" data-action="${a}">${ico(icon)}</button>`;
  const fixtures=[['海岸线 · 午后.jpg','3.8 MB',true],['暖墙与树影.jpg','2.4 MB',true],['一枝绿意.png','4.1 MB',false],['山间湖泊.webp','1.8 MB',true],['柠檬与水杯.jpg','2.1 MB',false],['旋转楼梯_用于文章封面_最终版本.png','5.6 MB',true],['一杯咖啡.jpg','2.7 MB',false],['沙丘 · 傍晚.jpg','3.2 MB',false],['林间微光.bmp','8.2 MB',false]].map((x,i)=>({id:i+1,name:x[0],size:x[1],linked:x[2],sprite:i,favorite:[1,3,7].includes(i+1)}));
  const initial=q.get('page')|| (mode==='m2'?'home':'library');
  const s={page:initial,images:fixtures,selected:new Set(),selecting:false,query:'',filter:'all',focus:1,returnPage:'library',op:'compress',format:'WebP',quality:'85',length:'1600',ratio:'3:2',order:[1,2],gap:'8',output:false,saved:false,exported:false,stage:0,targets:['catbox','imgbb'],batch:[],outputObjects:[],batchVersion:'原图',linkFormat:'URL',scenario:q.get('scenario')||'normal',modal:null,paused:false,canceled:false,settingSaved:false,cacheClean:false,restored:false,preferences:{network:'any',concurrency:'3',retention:'24'},draft:{network:'any',concurrency:'3',retention:'24'}};
  const allowed=['home','library','detail','links','tasks','accounts','settings','menu','picker','editor','targets','receipt'];if(!allowed.includes(s.page))s.page=mode==='m2'?'home':'library';
  let timer,previousFocus;const history=[];
  const image=id=>s.images.find(p=>p.id===Number(id));
  const ph=(p,cl='')=>`<div class="photo ${cl}" role="img" aria-label="${esc(p.name)}" style="--x:${p.sprite%3*50}%;--y:${Math.floor(p.sprite/3)*50}%"></div>`;
  const badge=(t,cl='')=>`<span class="badge ${cl}">${esc(t)}</span>`;
  const note=(t,kind='')=>`<div class="notice ${kind}">${ico('info')}<span>${t}</span></div>`;
  const os=()=>'<div class="osbar"><span>9:41</span><span>▰ ◔ ▰</span></div>';
  const header=(title,subtitle='',left='',right='')=>`<header class="apphead"><div class="row">${left}<div><h1>${esc(title)}</h1>${subtitle?`<small>${esc(subtitle)}</small>`:''}</div></div>${right}</header>`;
  const back=(target)=>ib('返回','back:'+target,'back');
  const nav=()=> s.selecting&&s.page==='library'?`<nav class="dock selectbar" aria-label="选中图片操作">${['compress','stitch','upload'].map((a,i)=>`<button data-action="${a}" ${s.selected.size?'':'disabled'}>${ico(['compress','stitch','upload'][i])}<span>${['压缩','拼接','上传'][i]}</span></button>`).join('')}${ib('更多操作','more-selected','menu')}</nav>`:`<nav class="dock" aria-label="主导航">${[['library','图库','image'],['links','链接','link'],['tasks','任务','upload']].map(([p,t,i])=>`<button class="${s.page===p?'active':''}" data-action="go:${p}" ${s.page===p?'aria-current="page"':''}>${ico(i)}<span>${t}</span></button>`).join('')}</nav>`;
  const menuButton=()=>ib('工具与设置','go:menu','menu');
  const filtered=()=>s.images.filter(p=>(s.filter==='all'||s.filter==='linked'&&linked(p)||s.filter==='favorite'&&p.favorite)&&p.name.toLowerCase().includes(s.query.toLowerCase()));
  Object.assign(s,{accounts:[{id:'catbox',provider:'catbox',name:'匿名',anonymous:true,enabled:true,hasCredential:false,validCredential:true,status:'anonymous'},{id:'imgbb',provider:'imgbb',name:'写作',anonymous:false,enabled:true,hasCredential:true,validCredential:false,status:'expired'}],nextAccountId:1,accountEdit:null,linkQuery:'',linkTarget:'all',linkVersion:'all',uploadSource:{kind:'original',ids:[]},results:[],draftBatch:null,nextVersion:1,nextResult:1,nextAssetId:10,nextTaskId:1,batches:[],linkResult:null,offline:s.scenario==='offline',unknownRetransmitted:false,saveAttempts:0,importAttempts:0});
  const extension=format=>({JPEG:'jpg',PNG:'png',WebP:'webp'}[format]||String(format).toLowerCase());
  function outputObjects(){const ext=extension(s.format),version='processed-'+s.nextVersion++;const ids=s.op==='stitch'?s.order:s.op==='crop'?[[...s.selected][0]||s.focus]:[...s.selected];const parents=ids.map(image);const make=(p,index,sourceIds)=>({...p,id:version+'-'+index,versionId:version+'-'+index,sourceIds,kind:'processed',format:s.format,name:(s.op==='stitch'?'拼接':p.name.replace(/\.[^.]+$/,''))+'_处理副本.'+ext,linked:false});return s.op==='stitch'?[make(parents[0],0,ids)]:parents.map((p,i)=>make(p,i,[p.id]));}
  const uploadObjects=()=>s.uploadSource.kind==='processed'?s.outputObjects.map(p=>({...p,sourceIds:[...p.sourceIds,...(p.savedAssetId?[p.savedAssetId]:[])]})):s.uploadSource.ids.map(id=>s.images.find(p=>p.id===id)).filter(Boolean).map(p=>({...p,versionId:p.versionId||'asset-'+p.id,sourceIds:[...new Set([p.id,...(p.sourceIds||[])])],kind:p.kind||'original'}));
  const uploadLabel=()=>s.uploadSource.kind==='processed'?'处理结果':uploadObjects().every(p=>p.kind==='processed')?'已保存处理副本':'原图';
  const account=id=>s.accounts.find(a=>a.id===id);
  const providerName=id=>id==='catbox'?'Catbox':'ImgBB';
  const targetName=id=>{const a=account(id);return a?providerName(a.provider)+' · '+a.name:'已移除目标';};
  const resultTargetName=r=>r.targetLabel||targetName(r.target);
  const resultUrl=r=>`https://${account(r.target)?.provider==='catbox'?'files':'images'}.example.test/${r.versionId}-${r.id}.${r.name.split('.').pop()}`;
  const putResult=(object,target,state)=>{const r={...object,sourceIds:[...object.sourceIds],id:'result-'+s.nextResult++,target,targetLabel:targetName(target),state,url:null,attempts:[{taskId:'task-'+s.nextTaskId++,state}]};if(state==='succeeded')r.url=resultUrl(r);s.results.push(r);return r;};
  for(const [id,target,state] of [[1,'catbox','succeeded'],[1,'imgbb','failed'],[2,'catbox','succeeded'],[2,'imgbb','succeeded'],[4,'catbox','unknown'],[6,'imgbb','succeeded']]){const p=image(id);putResult({...p,versionId:'asset-'+id,sourceIds:[id],kind:'original'},target,state);}
  const articleResults=()=>s.results.filter(r=>Number(r.id.slice(7))<=4);
  function summaryLabel(list){if(list.some(r=>r.state==='waiting'))return '等待联网';if(list.some(r=>r.state==='authorization'))return '等待账号条件';if(list.some(r=>r.state==='paused'))return '已暂停';if(list.some(r=>r.state==='unknown'))return '待确认';if(list.length&&list.every(r=>r.state==='succeeded'))return '全部成功';if(list.some(r=>r.state==='succeeded'))return '部分成功';if(list.length&&list.every(r=>r.state==='canceled'))return '已取消';return '失败';}
  const linked=p=>s.results.some(r=>r.state==='succeeded'&&r.sourceIds.includes(p.id));
  const versionLabel=r=>r.kind==='processed'?'处理版本 '+r.versionId.slice(10).split('-')[0]:'原图';
  function dispatchState(id){const a=account(id);if(!a||a.deleted||!a.enabled||!a.anonymous&&!a.hasCredential)return 'authorization';if(!a.validCredential)return 'failed';if(!a.anonymous)a.status='usable';return 'succeeded';}
  const pendingState=state=>['waiting','paused','authorization'].includes(state);
  const accountImpact=id=>s.results.filter(r=>r.target===id&&pendingState(r.state)).length;
  function suspendAccount(id){for(const r of s.results)if(r.target===id&&r.state==='waiting'){r.state='authorization';r.attempts.at(-1).state='authorization';}}
  function setUpload(kind,ids=[]){s.uploadSource={kind,ids:[...ids]};}
  function invalidate(){s.output=false;s.outputObjects=[];s.saved=false;s.exported=false;}
  function rememberBatch(){s.draftBatch={selected:[...s.selected],op:s.op,format:s.format,quality:s.quality,length:s.length,ratio:s.ratio,order:[...s.order],gap:s.gap,output:s.output,outputObjects:s.outputObjects,saved:s.saved,exported:s.exported};}
  function resumeBatch(){if(!s.draftBatch)return go('picker');const d=s.draftBatch;for(const k of ['op','format','quality','length','ratio','gap','output','outputObjects','saved','exported'])s[k]=d[k];s.order=[...d.order];s.selected=new Set(d.selected);go('editor');}
  function startBatch(){const objects=uploadObjects();if(!objects.length)return toast('没有可上传对象，请重新选择');if(!s.targets.length)return toast('至少选择一个上传目标');if(s.targets.some(id=>!account(id)||account(id).deleted||!account(id).enabled))return toast('所选目标已停用或移除，请重新核对目标');s.batchVersion=objects.every(p=>p.kind==='processed')?'处理结果':objects.some(p=>p.kind==='processed')?'原图与处理结果':'原图';s.batch=objects.flatMap(p=>s.targets.map(target=>putResult(p,target,s.offline?'waiting':dispatchState(target))));s.batches.push({items:s.batch,version:s.batchVersion});close();s.selecting=false;go(mode==='m2'?'receipt':'tasks');toast(s.offline?'任务已排队，等待联网（演示）':'模拟结果按图片版本和目标独立记录');return true;}
  function retryResults(list){if(s.offline)return toast('当前离线，失败项保留');let count=0;for(const r of list)if(r.state==='failed'){const state=dispatchState(r.target);r.attempts.push({taskId:'task-'+s.nextTaskId++,state});r.state=state;if(state==='succeeded'){r.url=resultUrl(r);count++;}}render();toast(count?'已模拟重试失败目标；原失败尝试与成功链接保留':'未取得成功结果，请核对对应账号状态');}
  function settleWaiting(list){if(s.offline)return;for(const r of list)if(['waiting','authorization'].includes(r.state)){r.state=dispatchState(r.target);r.attempts.at(-1).state=r.state;if(r.state==='succeeded')r.url=resultUrl(r);}}
  function resultRows(list){return list.map(r=>`<div class="target"><div class="grow"><strong>${esc(r.name)}</strong><small>${versionLabel(r)} · ${esc(resultTargetName(r))} · #${esc(r.target)}</small>${r.state==='authorization'?`<small>${account(r.target)?.deleted?'原目标已移除；取消剩余排队后另建发布，不能用同名账号接管。':!account(r.target)?.enabled?'原目标已停用；启用该身份后继续。':'原目标缺少凭据；补充配置后检查条件。'}</small>`:''}${r.attempts.length>1?`<small>尝试记录：${r.attempts.map(a=>a.taskId+' '+({failed:'失败',succeeded:'成功',waiting:'等待',authorization:'等待授权条件',paused:'已暂停',canceled:'已取消',unknown:'待确认'}[a.state]||a.state)).join(' → ')}</small>`:''}</div>${badge(({succeeded:'成功',failed:'授权失效',waiting:'等待联网',paused:'已暂停',canceled:'已取消',authorization:'等待授权条件',unknown:'待确认'})[r.state]||r.state,r.state==='failed'?'error':r.state==='succeeded'?'':'warn')}${r.state==='succeeded'?`<button class="textbtn" data-action="link:${r.id}">链接</button>`:''}</div>`).join('');}
  function batchCard(){if(!s.batch.length)return '';const ok=s.batch.filter(t=>t.state==='succeeded').length,waiting=s.batch.some(t=>t.state==='waiting'),authorization=s.batch.some(t=>t.state==='authorization'),paused=s.batch.some(t=>t.state==='paused'),canceled=s.batch.some(t=>t.state==='canceled');return `<section class="task" id="current-batch"><div class="row between"><h2>本次上传</h2>${badge(summaryLabel(s.batch),ok===s.batch.length?'':'warn')}</div><p>${s.batchVersion} · ${ok}/${s.batch.length} 项成功</p>${resultRows(s.batch)}<div class="row">${btn('查看成功链接','copy-batch','outline','copy',ok?'':'disabled')}${s.batch.some(t=>['failed','authorization'].includes(t.state))?btn('修复账号','go:accounts')+(s.batch.some(t=>t.state==='failed')?btn('仅重试本次失败','retry-batch'):''):''}${waiting?btn('模拟恢复联网','online'):''}${authorization?btn('检查账号条件并继续','resume-authorized','outline'):''}${waiting||paused||authorization?btn(paused?'继续本次排队':'暂停本次排队','pause-current','outline')+btn('取消本次排队','cancel-current','outline'):''}</div></section>`;}
  function olderBatches(){return s.batches.slice(0,-1).map((b,i)=>{const ok=b.items.filter(r=>r.state==='succeeded').length;return '<section class="task"><h2>历史上传 '+(i+1)+'</h2><p>'+b.version+' · '+ok+'/'+b.items.length+' 项成功</p>'+resultRows(b.items)+'<div class="row">'+(ok?btn('查看这批成功链接','copy-older:'+i,'outline'):'')+(b.items.some(r=>r.state==='failed')?btn('重试这批失败项','retry-older:'+i):'')+(b.items.some(r=>r.state==='waiting')?btn('模拟恢复联网','online'):'')+(b.items.some(r=>pendingState(r.state))?btn(b.items.some(r=>r.state==='paused')?'继续这批排队':'暂停这批排队','pause-older:'+i,'outline')+btn('取消这批排队','cancel-older:'+i,'outline'):'')+'</div></section>';}).join('');}
  const tile=p=>`<button class="tile ${s.selected.has(p.id)?'selected':''}" data-action="photo:${p.id}" aria-label="${s.selecting?'选择 ':''}${esc(p.name)}" ${s.selecting?`aria-pressed="${s.selected.has(p.id)}"`:''}>${ph(p)}<span class="check">${s.selected.has(p.id)?'✓':''}</span>${linked(p)?`<span class="link-dot">${ico('link')}</span>`:''}</button>`;
  function library(){
    const list=filtered();
    return header(s.selecting?`已选 ${s.selected.size} 张`:'图库',s.selecting?'选择图片后，在底部继续':s.images.length+' 张图片 · 本机独立副本',mode==='m2'?back('home'):'',s.selecting?'<button class="textbtn" data-action="select-off">完成</button>':`<div class="row"><button class="textbtn" data-action="select-on">选择</button>${ib('导入图片','import','plus','tint')}${menuButton()}</div>`)+`<label class="search">${ico('search')}<input id="search" placeholder="搜索图片名称" aria-label="搜索图片" value="${esc(s.query)}"></label><div class="filters">${[['all','全部'],['favorite','收藏'],['linked','有链接']].map(([v,t])=>`<button class="filter ${s.filter===v?'active':''}" data-action="filter:${v}">${t}</button>`).join('')}</div><main class="content compact ${s.selecting?'selecting':''}">${s.scenario==='permission'?note('系统照片访问受限。已保管图片仍可浏览；重新导入可改用文件选择。'):''}${list.length?`<section class="day"><h2>今天<small>10 月 3 日</small></h2></section><div class="tiles">${list.map(tile).join('')}</div><div class="library-foot">导入后保留独立副本，用户原文件保留。<br>点图看详情；“选择”进入批量操作。</div>`:`<div class="empty">${ico('search')}<h2>没有匹配图片</h2><p>试试其他名称或清除筛选。</p>${btn('清除筛选','clear-search')}</div>`}</main>`;
  }
  function home(){return header('ImageHost','本地个人图片工具','',menuButton())+`<main class="content"><section class="welcome"><h1>这次，准备发什么？</h1><p>选几张图片，处理好，再拿到链接。</p></section><section class="newbatch"><h2>${s.draftBatch?`继续这 ${s.draftBatch.selected.length} 张图片`:'开始一次发布'}</h2><div class="flow"><span>① 选图</span><span>→</span><span>② 可选处理</span><span>→</span><span>③ 发布</span></div>${btn(s.draftBatch?'继续当前批次':'添加图片',s.draftBatch?'resume':'go:picker','primary','plus')}<p class="quietcopy">导入即永久保管；批次只是操作上下文。</p></section><div class="shortcuts"><button data-action="go:library">${ico('image')}应用图库${ico('next')}</button><button data-action="go:links">${ico('link')}已获链接${ico('next')}</button></div><button class="activity" data-action="go:tasks">${ico('upload')}<span class="grow"><strong>文章配图 · ${summaryLabel(articleResults())}</strong><p>${articleResults().filter(r=>r.state==='succeeded').length}/4 项成功</p></span>${ico('next')}</button><h2 class="section-title">最近保存<small>应用副本</small></h2>${s.images.slice(-2).reverse().map(p=>`<button class="fileline" data-action="detail:${p.id}">${ph(p,'thumb')}<span class="grow"><strong>${esc(p.name)}</strong><small>${p.size} · 今天</small></span>${ico('next')}</button>`).join('')}<div class="toolslist"><button data-action="go:settings">${ico('settings')}<span>本地存储与设置</span>${ico('next')}</button></div></main>`;}
  function picker(){const list=s.images.filter(p=>p.name.toLowerCase().includes(s.query.toLowerCase()));return header('选择图片',`已选 ${s.selected.size} 张`,back('home'),'<button class="textbtn" data-action="import">导入</button>')+`<div class="stepper"><span class="active">1 选图</span><span>2 处理</span><span>3 发布</span></div><label class="search">${ico('search')}<input id="search" placeholder="搜索图片名称" aria-label="搜索图片" value="${esc(s.query)}"></label><div class="filters">${btn('全选当前结果','select-all','outline')}${btn('取消全部选择','clear-selection','outline')}</div><main class="content">${note('从全部应用图库选择；新导入先保存独立副本。','info')}<div class="tiles pick-grid selecting">${list.map(p=>`<div>${tile(p)}<div class="pick-name">${esc(p.name)}</div></div>`).join('')}</div>${list.length?'':'<p>没有匹配图片。清除搜索后重试。</p>'}</main><div class="sticky-action">${btn(`下一步 · ${s.selected.size} 张`,'picker-next','primary wide','next',s.selected.size?'':'disabled')}</div>`;}
  function detail(){const p=image(s.focus);if(!p)return header('图片详情','',back('library'))+'<main class="content">图片已删除。</main>';const list=s.results.filter(r=>r.sourceIds.includes(p.id));return header('图片详情','',back(s.returnPage),ib(p.favorite?'取消收藏':'收藏','favorite','star'))+`<main class="content compact">${ph(p,'detail-image')}<div style="padding:0 20px"><h2 class="detail-title">${esc(p.name)}</h2><p class="meta">${p.size} · ${p.name.split('.').pop().toUpperCase()} · 本机副本已保管${p.versionId?' · '+versionLabel(p):''}</p><div class="action-grid">${btn('编辑副本','detail-edit','','crop')}${btn(p.kind==='processed'?'上传已保存副本':'上传原图','detail-upload','','upload')}</div><h2 class="section-title">远程结果<small>原图与处理版本分别记录</small></h2>${list.length?resultRows(list):note('尚无远程结果，上传后可在这里查看。','info')}<div class="toolslist"><button data-action="delete">${ico('trash')}<span>删除本机图库记录<small>保留用户原文件与远程文件</small></span>${ico('next')}</button></div></div></main>`;}
  function filteredLinks(){const text=s.linkQuery.trim().toLowerCase();return s.results.filter(r=>r.state==='succeeded'&&(s.linkTarget==='all'||r.target===s.linkTarget)&&(s.linkVersion==='all'||r.kind===s.linkVersion)&&[r.name,r.url,resultTargetName(r),versionLabel(r)].some(v=>String(v||'').toLowerCase().includes(text))).sort((a,b)=>Number(b.id.slice(7))-Number(a.id.slice(7)));}
  function links(){const all=s.results.filter(r=>r.state==='succeeded'),list=filteredLinks(),ids=[...new Set(all.map(r=>r.target))];return header('链接',`找到 ${list.length} / ${all.length} 条成功结果`,mode==='m2'?back('home'):'',menuButton())+`<label class="search">${ico('search')}<input id="link-search" placeholder="搜索名称、账号或链接" aria-label="搜索链接" value="${esc(s.linkQuery)}"></label><div class="link-filters"><label><span>目标身份</span><select id="link-target" aria-label="筛选链接账号"><option value="all">全部账号</option>${ids.map(id=>{const r=all.find(r=>r.target===id);return `<option value="${id}" ${s.linkTarget===id?'selected':''}>${esc(resultTargetName(r))} · #${esc(id)}</option>`;}).join('')}</select></label><label><span>图片版本</span><select id="link-version" aria-label="筛选链接版本">${[['all','全部版本'],['original','原图'],['processed','处理结果']].map(([id,t])=>`<option value="${id}" ${s.linkVersion===id?'selected':''}>${t}</option>`).join('')}</select></label></div><main class="content">${list.length?btn(`复制这 ${list.length} 条结果`,'copy-filtered','outline wide','copy'):''}<p class="quietcopy">最新结果在前；只搜索普通远程链接，不包含凭据。</p>${list.map(r=>`<button class="fileline" data-action="link:${r.id}">${ph(r,'thumb')}<span class="grow"><strong>${esc(r.name)}</strong><small>${esc(resultTargetName(r))} · ${versionLabel(r)}</small><small>目标 #${esc(r.target)} · ${r.id}</small></span>${ico('copy')}</button>`).join('')}${list.length?'':`<div class="empty">${ico('search')}<h2>${all.length?'没有匹配链接':'还没有成功链接'}</h2><p>${all.length?'调整关键词或筛选。已有记录仍保留。':'选图上传成功后，可以在这里回访。'}</p>${all.length?btn('清除链接筛选','clear-link-search'):btn('去应用图库','go:library')}</div>`}</main>`;}
  function articleCard(){const rows=articleResults(),ok=rows.filter(r=>r.state==='succeeded').length;return `<section class="task" id="article-history"><div class="row between"><h2>文章配图</h2>${badge(summaryLabel(rows),ok===rows.length?'':'warn')}</div><p>${ok}/${rows.length} 项成功 · 历史发布</p>${resultRows(rows)}<div class="row">${ok?btn('复制这批成功链接','copy-history','outline','copy'):''}${rows.some(r=>['failed','authorization'].includes(r.state))?btn('修复账号','go:accounts','outline'):''}${rows.some(r=>r.state==='failed')?btn('仅重试失败项','retry','','history'):''}${rows.some(r=>r.state==='authorization')?btn('检查原账号条件','resume-history','outline'):''}${rows.some(r=>pendingState(r.state))?btn('取消历史等待项','cancel-history','outline'):''}</div></section>`;}
  function tasks(receipt=false){if(receipt)return header('发布结果','逐张图片 · 逐个目标确认',back('home'),menuButton())+'<main class="content"><section class="receipt"><h2>本次发布结果</h2><p class="meta">'+esc(s.batchVersion)+' · '+s.batch.length+' 个独立目标结果</p></section>'+batchCard()+btn('完成，回到工作台','go:home','primary wide')+'</main>';return header(receipt?'发布结果':'上传任务',receipt?'逐张图片 · 逐个目标确认':'离开页面，任务记录仍可查看',back(mode==='m2'?'home':'library'),menuButton())+`<main class="content">${batchCard()}${olderBatches()}${s.offline?note('当前离线。等待联网后继续，不影响本地图片。'):''}${receipt?`<section class="receipt"><div class="row"><span class="recnum">${ico('check')}</span><div><h2>已获得部分链接</h2><span class="meta">${s.targets.length} 个上传目标 · 演示结果</span></div></div><div class="row">${btn('复制成功链接','copy-batch','primary','copy')}${btn('回到图库','go:library','outline')}</div></section>`:''}${articleCard()}<section class="task"><div class="row between"><h2>旅行照片</h2>${badge('待确认','warn')}</div><p>山间湖泊.webp · Catbox</p>${note('提交后连接中断，未收到确认。远端可能已经生成文件。')}${btn('查看处理选项','unknown','outline')}</section><section class="task"><div class="row between"><h2>日常素材</h2>${badge(s.canceled?'已取消':s.paused?'已暂停':'进行中','muted')}</div><p>一杯咖啡.jpg · Catbox / ImgBB</p><div class="progress"><i style="width:${s.canceled?'0':'62'}%"></i></div><div class="row">${btn(s.paused?'继续':'暂停','pause','outline','pause',s.canceled?'disabled':'')}${btn('取消任务','cancel','outline','close',s.canceled?'disabled':'')}</div></section><p class="demo-note">模拟任务。正式后台执行由系统条件决定，不承诺持续运行。</p></main>`;}
  function menu(){const entries=[['library','应用图库','永久保存的本机副本','image'],['links','远程链接','原图与处理版本分别记录','link'],['tasks','上传任务','查看暂停、失败和待确认','upload'],['accounts','图床账号','Catbox / ImgBB','cloud'],['settings','存储与设置','备份、恢复与诊断','settings']];return header('工具与设置','',back(mode==='m2'?'home':'library'))+`<main class="content full-menu">${s.draftBatch?btn('继续处理批次','resume','primary wide')+btn('清空处理批次','clear-batch','outline wide'):''}<div class="toolslist">${entries.map(([p,t,sub,i])=>`<button data-action="go:${p}">${ico(i)}<span><strong>${t}</strong><small>${sub}</small></span>${ico('next')}</button>`).join('')}</div><p class="quietcopy">没有应用云端账户。本地功能可独立使用。<br>未来同步不属于首版界面。</p></main>`;}
  function accountStatus(a){return !a.enabled?'已停用':a.anonymous?'匿名目标':a.status==='expired'?'授权失效':a.status==='usable'?'模拟上传成功':'未验证';}
  function accounts(){return header('图床账号','每个上传目标有独立身份',back('menu'),ib('添加图床账号','add-account','plus','tint'))+`<main class="content"><p class="quietcopy">个人图床配置，无需应用云端账户。凭据仅用于主动上传。</p>${s.accounts.filter(a=>!a.deleted).map(a=>`<section class="account"><div class="row between"><h2>${esc(targetName(a.id))}</h2>${badge(accountStatus(a),!a.enabled?'muted':a.status==='expired'?'error':a.status==='unverified'?'warn':'')}</div><p class="meta">目标 #${esc(a.id)} · ${a.anonymous?'不使用账号凭据':'示例配置，不保存任何真实秘密'}<br>${accountImpact(a.id)} 项等待任务使用此身份。</p><div class="account-actions">${a.anonymous?btn('能力说明','catbox-info','outline'):btn(a.status==='expired'?'重新配置':'编辑配置','credential:'+a.id,'outline')}${btn(a.enabled?'停用':'启用','toggle-account:'+a.id,'outline')}${a.anonymous?'':btn('移除','remove-account:'+a.id,'textbtn')}</div></section>`).join('')}${note('新填凭据仅标记未验证。原型不请求官方验证，也不会自动上传图片验证。','info')}${note('停用或移除配置保留历史链接；不会删除图床文件。服务限制与保留期限按图床实际能力提示。','info')}</main>`;}
  function settings(){return header('存储与设置','仅此设备',back('menu'))+`<main class="content"><h2 class="section-title">本机空间<small>示例数值</small></h2><p><strong>2.4 GB</strong> 永久图片 · <strong>${s.cacheClean?'0':'128 MB'}</strong> 临时缓存</p><div class="toolslist"><button data-action="cache">${ico('folder')}<span>清理过期缓存<small>保留永久图片与活跃任务依赖</small></span>${ico('next')}</button><button data-action="backup">${ico('cloud')}<span>导出完整备份<small>图库整理信息 + 永久图片</small></span>${ico('next')}</button><button data-action="restore">${ico('history')}<span>恢复备份<small>先检查备份，再确认替换</small></span>${ico('next')}</button></div><h2 class="section-title">上传偏好</h2><label class="setting"><span>网络条件<small>系统不支持时明确提示</small></span><select data-field="network" aria-label="网络条件"><option value="any" ${s.draft.network==='any'?'selected':''}>允许联网</option><option value="unmetered" ${s.draft.network==='unmetered'?'selected':''}>非计费网络</option></select></label><label class="setting"><span>并发上限</span><select data-field="concurrency" aria-label="并发上限">${['1','2','3'].map(v=>`<option ${s.draft.concurrency===v?'selected':''}>${v}</option>`).join('')}</select></label>${btn('保存设置','save-settings','primary wide')}<p class="quietcopy">${s.settingSaved?'设置已保存到演示会话。':'修改后点击保存。'}刷新原型会恢复示例数据。</p><div class="toolslist"><button data-action="diagnostics">${ico('info')}诊断与日志${ico('next')}</button></div></main>`;}
  function editor(){const ids=[...s.selected];const a=image(ids[0]||s.focus);const b=image(ids[1]||2);return header(s.op==='crop'?'裁剪副本':s.op==='stitch'?'拼接副本':`压缩 ${Math.max(ids.length,1)} 张图片`,'',back(mode==='m2'?'picker':s.returnPage),'<button class="textbtn" data-action="discard">退出</button>')+`<main><div class="stage-preview ${s.op==='crop'?'cropped':s.op==='stitch'?'stitched':''}">${s.op==='stitch'?s.order.map(id=>ph(image(id))).join(''):ph(a)}<span class="preview-label">示意画布 · 原图保留</span></div><div class="editor-panel"><div class="editor-tabs">${[['compress','压缩'],['crop','裁剪'],['stitch','拼接']].map(([v,t])=>`<button class="${s.op===v?'active':''}" data-action="op:${v}">${t}</button>`).join('')}</div>${s.op==='compress'?`<label class="field"><span>输出格式</span><select data-field="format" aria-label="输出格式">${['WebP','JPEG','PNG'].map(v=>`<option ${s.format===v?'selected':''}>${v}</option>`).join('')}</select></label><label class="field"><span>最长边（像素）</span><input type="number" min="1" max="12000" data-field="length" aria-label="最长边" value="${s.length}"></label><p class="meta">质量 ${s.quality} · 保持比例，不放大原图。<br>透明图转 JPEG 须先确认背景；动画不在此静态流程中处理。</p>`:s.op==='crop'?`<label class="field"><span>裁剪比例</span><select data-field="ratio" aria-label="裁剪比例">${['3:2','1:1','4:5'].map(v=>`<option ${s.ratio===v?'selected':''}>${v}</option>`).join('')}</select></label><p class="meta">当前图片：${esc(a.name)}<br>裁剪单张；多选时只处理当前图片，其他图片保留。</p>`:`<div class="setting"><span>拼接顺序</span><button class="textbtn" data-action="swap-order">反转顺序</button></div><label class="field"><span>间距（像素）</span><input type="number" min="0" max="200" data-field="gap" aria-label="拼接间距" value="${s.gap}"></label><div class="order-list">${s.order.map((id,i)=>`<div class="setting"><span>${i+1}. ${esc(image(id).name)}</span><button class="iconbtn" aria-label="上移 ${esc(image(id).name)}" data-action="move:${id}:-1" ${i?'':'disabled'}>↑</button><button class="iconbtn" aria-label="下移 ${esc(image(id).name)}" data-action="move:${id}:1" ${i===s.order.length-1?'disabled':''}>↓</button></div>`).join('')}</div><p class="meta">${s.order.map(id=>esc(image(id).name)).join(' → ')}<br>横向等高拼接，浅色背景；预览只显示构图。</p>`}${s.op!=='compress'?`<label class="field"><span>输出格式</span><select data-field="format" aria-label="输出格式">${['WebP','JPEG','PNG'].map(v=>`<option ${s.format===v?'selected':''}>${v}</option>`).join('')}</select></label>`:''}${s.output?`<section class="process-result"><strong>处理结果已生成</strong><span>演示输出 · ${s.saved?'已永久保存至图库':'尚未永久保存'}</span><div class="row">${btn(s.saved?'已保存':'保存到图库','save-result',s.saved?'outline':'', '',s.saved?'disabled':'')}${btn('导出副本','export-result','outline')}</div>${s.exported?'<p>导出操作已演示；未写入系统文件。</p>':''}</section>`:''}</div></main><div class="sticky-action"><div class="row">${s.output?btn('上传结果','output-upload','primary'):btn('生成结果','generate','primary','edit')}${mode==='m2'?btn('跳过处理','skip-processing','outline'):''}</div></div>`;}
  function targets(){return header('发布到图床','开始前确认上传对象',back('editor'))+`<div class="stepper"><span>1 选图</span><span>2 处理</span><span class="active">3 发布</span></div><main class="content">${note('本次上传 '+uploadLabel()+'。永久原图仍保留。','info')}<h2 class="section-title">上传对象<small>${uploadLabel()}</small></h2>${uploadObjects().map(p=>`<div class="fileline">${ph(p,'thumb')}<span class="grow"><strong>${esc(p.name)}</strong><small>${p.kind==='processed'?'处理副本':'原图'} · ${s.uploadSource.kind==='processed'?'临时结果':'应用本机副本'}</small></span></div>`).join('')}<h2 class="section-title">上传目标<small>按身份多选</small></h2>${targetsChecks()}<p class="quietcopy">新增账号不会自动加入选择或既有批次。图片×目标独立记录结果。</p></main><div class="sticky-action">${btn('开始上传','start-upload','primary wide','upload')}</div>`;}
  function targetsChecks(){return s.accounts.filter(a=>!a.deleted&&(a.enabled||s.targets.includes(a.id))).map(a=>`<label class="checkrow"><input type="checkbox" data-target="${a.id}" ${s.targets.includes(a.id)?'checked':''}><span><strong>${esc(targetName(a.id))}</strong><small>目标 #${esc(a.id)} · ${accountStatus(a)}${!a.enabled?'；请取消选择或先启用':''}</small></span></label>`).join('')||'<p>没有可用配置，请前往图床账号添加或启用。</p>';}
  function render(){if(s.page==='editor')rememberBatch();const pages={home,library,picker,detail,links,tasks,menu,accounts,settings,editor,targets,receipt:()=>tasks(true)};document.querySelector('#demo').innerHTML=`<div><strong>${mode==='m1'?'M1 · 图库优先':'M2 · 发布工作台'}</strong><p>同色系，比较真实交互结构。所有业务操作为模拟。</p></div><div><a href="index.html">对比</a><a href="prototype.html?mode=${mode==='m1'?'m2':'m1'}">切换方案</a><a href="https://www.figma.com/design/ZZNCFyIONSibWLmRj2yexD" target="_blank" rel="noreferrer">Figma</a></div>`;document.querySelector('#phone').innerHTML=`<div class="phone ${s.page==='editor'?'editor':''}" data-mode="${mode}" data-page="${s.page}">${os()}${pages[s.page]()}${mode==='m1'&&['library','links','tasks'].includes(s.page)?nav():''}</div>`;renderModal();}
  const toast=t=>{const el=document.querySelector('#toast');el.textContent=t;el.className='on';clearTimeout(timer);timer=setTimeout(()=>{el.className='';},3500);};
  function go(p){if(s.page!==p)history.push(s.page);s.page=p;if(p==='picker')s.selecting=true;if(p==='library')s.selecting=false;render();window.scrollTo(0,0);}
  function open(name){previousFocus=document.activeElement;s.modal=name;renderModal();const e=document.querySelector('.sheet button,.sheet input');if(e)e.focus();}
  function close(){s.modal=null;renderModal();if(previousFocus&&previousFocus.isConnected)previousFocus.focus();}
  function renderModal(){document.querySelector('#phone').inert=!!s.modal;const layer=document.querySelector('#overlay');if(!s.modal){layer.innerHTML='';return;}let title='',body='';
    if(s.modal==='import'){title='添加到应用图库';body=`<p>选择来源后，应用保存独立本机副本，原文件保留。本原型使用合成样本。</p>${btn('从系统照片选择','mock-photo-import','primary wide','image')}${btn('从文件选择','mock-import','outline wide','folder')}${s.scenario==='permission'?note('系统照片权限受限。可使用文件来源，或前往系统设置授权。'):''}`;}
    if(s.modal==='upload'){title='上传选中图片';body=`<p>${uploadObjects().length} 个${uploadLabel()}。选好目标后开始上传。</p>${uploadObjects().map(p=>`<p><strong>${esc(p.name)}</strong> · ${p.kind==='processed'?'处理结果':'原图'}</p>`).join('')}${targetsChecks()}${btn('开始上传','start-upload','primary wide','upload')}`;}
    if(s.modal==='unknown'){title='远程结果待确认';body=`<p>提交后连接中断，服务可能已保存图片。先检查远端记录，再决定是否重传。</p>${note('重新上传可能生成重复远程文件。')}<label class="checkrow"><input id="duplicate-risk" type="checkbox"><span>我已了解重复上传的风险</span></label>${btn('重新上传','unknown-retry','primary wide')}${btn('保留待确认记录','close','outline wide')}`;}
    if(s.modal==='links'){const p=s.results.find(r=>r.id===s.linkResult);title='复制远程链接';body=`<p>${esc(p.name)} · ${versionLabel(p)} · ${esc(resultTargetName(p))} · 目标 #${esc(p.target)}</p><div class="links-format">${['URL','Markdown','HTML','BBCode'].map(v=>`<button class="filter ${s.linkFormat===v?'active':''}" data-action="format:${v}">${v}</button>`).join('')}</div><pre>${esc(linkText(p))}</pre>${btn('复制此链接','copy-one','primary wide','copy')}<p>此处演示复制反馈，不写入系统剪贴板。</p>`;}
    if(s.modal==='batch-links'){title='成功链接';body=`<div class="links-format">${['URL','Markdown','HTML','BBCode'].map(v=>`<button class="filter ${s.linkFormat===v?'active':''}" data-action="format:${v}">${v}</button>`).join('')}</div><p>${s.copyResults.length} 条成功结果；失败与待确认项不参与复制。</p><pre>${esc(s.copyResults.map(linkText).join('\n'))}</pre>${btn('复制这些成功链接','copy-summary','primary wide','copy')}`;}
    if(s.modal==='delete'){title='删除本机图库记录？';body=`<p>仅移除此图片在应用中的记录及本机副本，不删除用户原文件或远程图床文件。活跃任务依赖会阻止删除。</p>${btn('删除本机记录','confirm-delete','danger wide')}${btn('保留图片','close','outline wide')}`;}
    if(s.modal==='more-selected'){title=`已选 ${s.selected.size} 张`;body=`${btn('查看首张图片','selected-detail','outline wide','image')}${btn('全选当前筛选结果','select-all','outline wide')}${btn('取消选择','select-off','outline wide')}`;}
    if(s.modal==='credential'){const a=account(s.accountEdit);title=a?'编辑图床配置':'新增图床配置';body=`<p>只演示配置流程，请勿输入真实凭据。不会向图床发出验证请求。</p>${a?`<p>目标 #${esc(a.id)} · 修改后身份保持不变；历史结果名称保留。</p>`:`<label class="field"><span>图床服务</span><select id="account-provider" aria-label="图床服务"><option value="imgbb">ImgBB</option><option value="catbox">Catbox 账号</option></select></label>`}<label class="field"><span>账号显示名称</span><input id="account-name" value="${esc(a?.name||'')}" placeholder="例如：写作" autocomplete="off"></label><label class="field"><span>新的示例凭据${a?'（留空保留原配置）':''}</span><input id="mock-key" type="password" placeholder="输入任意演示字符" autocomplete="off"></label>${btn('保存示例配置','save-credential','primary wide')}`;}
    if(s.modal==='account-disable'||s.modal==='account-remove'){const a=account(s.accountEdit),remove=s.modal==='account-remove';title=(remove?'移除':'停用')+'此图床配置？';body=`<p>${esc(targetName(a.id))} · 目标 #${esc(a.id)}</p>${note(`有 ${accountImpact(a.id)} 项等待任务使用此身份。后续请求将停止，不能改派给其他账号。`)}<p>${remove?'移除配置与示例凭据；历史目标名称、成功链接和图片保留。':'可重新启用同一身份；历史链接保留。'}不会请求删除远程文件。</p>${btn(remove?'确认移除配置':'确认停用配置',remove?'confirm-remove-account':'confirm-disable-account','danger wide')}${btn('保留配置','close','outline wide')}`;}
    if(s.modal==='catbox-info'){title='Catbox 目标说明';body='<p>匿名上传和账号上传为不同目标身份。是否支持远程查询、删除或保留，应按实际图床能力判断。</p>'+btn('知道了','close','primary wide');}
    if(s.modal==='cache'){title='清理过期临时结果';body=`<p>可以清理 ${s.cacheClean?'0':'128 MB'} 过期临时缓存。永久图片、已保存处理结果和活跃任务依赖保留。</p>${btn('清理临时缓存','confirm-cache','primary wide')}`;}
    if(s.modal==='backup'){title='导出完整本地备份';body='<p>包含永久图片和整理信息。凭据与正在执行的任务不作为普通可移植数据。</p>'+btn('演示导出备份','confirm-backup','primary wide');}
    if(s.modal==='restore'){title='备份检查通过 · 演示';body=note('恢复前需暂停任务，并保留当前有效数据的保护副本。此原型不读写备份文件。')+'<p>9 张永久图片 · 4 条远程结果。检验后确认恢复。</p>'+btn('确认恢复演示数据','confirm-restore','primary wide');}
    if(s.modal==='diagnostics'){title='诊断与日志';body='<p>记录错误类型、时间和任务编号。凭据、敏感路径和签名链接脱敏。</p><pre>14:32 task-demo-1 / AUTH_EXPIRED\ncredential: [REDACTED]\npath: [LOCAL_PATH]</pre>'+btn('演示复制诊断','copy-diagnostics','outline wide');}
    if(s.modal==='discard'){title='离开当前处理？';body='<p>保留当前批次和参数，未保存处理结果仍为临时输出。再次进入可以继续。</p>'+btn('保留并离开','confirm-discard','primary wide')+btn('继续处理','close','outline wide');}
    if(s.modal==='flatten'){title='JPEG 会丢失透明度';body='<p>当前选择包含 PNG。只有确认白色背景后才能生成 JPEG 副本，原图保留。</p>'+btn('确认白色背景','confirm-generate','primary wide')+btn('保持原参数','close','outline wide');}
    layer.innerHTML=`<div class="modal-layer"><section class="sheet" role="dialog" aria-modal="true" aria-labelledby="sheet-title"><div class="handle"></div><div class="close-row"><h2 id="sheet-title">${title}</h2>${ib('关闭弹层','close','close')}</div>${body}</section></div>`;
  }
  function linkText(r){const url=r.url||'';const alt=r.name.replace(/[[\]\\]/g,c=>'\\'+c);const attr=value=>value.replace(/["&<>]/g,c=>({'"':'&quot;','&':'&amp;','<':'&lt;','>':'&gt;'}[c]));return s.linkFormat==='Markdown'?'!['+alt+']('+url+')':s.linkFormat==='HTML'?'<img src="'+attr(url)+'" alt="'+attr(r.name)+'">':s.linkFormat==='BBCode'?'[img]'+url+'[/img]':url;}
  function edit(op){if(!s.selected.size)s.selected.add(s.focus);if(op==='stitch'&&s.selected.size<2)return toast('请至少选择两张图片');const next=[...s.selected];const changed=!s.draftBatch||s.op!==op||JSON.stringify(next)!==JSON.stringify(s.draftBatch.selected);s.returnPage=s.page==='detail'?'detail':mode==='m2'?'picker':'library';s.op=op;if(changed){s.order=next;invalidate();}go('editor');}
  function onAction(a){
    if(a.startsWith('back:')){close();const p=history.pop()||a.slice(5);s.page=p;if(p==='picker')s.selecting=true;if(p==='library')s.selecting=false;render();window.scrollTo(0,0);return;}
    if(a.startsWith('go:')){close();go(a.slice(3));return;}
    if(a.startsWith('filter:')){s.filter=a.slice(7);render();return;}
    if(a.startsWith('photo:')){const id=Number(a.slice(6));if(s.selecting||s.page==='picker'){s.selected.has(id)?s.selected.delete(id):s.selected.add(id);render();}else{s.focus=id;s.returnPage='library';go('detail');}return;}
    if(a.startsWith('detail:')){s.focus=Number(a.slice(7));s.returnPage=s.page;go('detail');return;}
    if(a.startsWith('link:')){s.linkResult=a.slice(5);const r=s.results.find(r=>r.id===s.linkResult);if(r?.state==='succeeded')open('links');else toast('该结果还没有成功链接');return;}
    if(a.startsWith('format:')){s.linkFormat=a.slice(7);renderModal();document.querySelector('.sheet [data-action="format:'+s.linkFormat+'"]').focus();return;}
    if(a.startsWith('credential:')){s.accountEdit=a.slice(11);open('credential');return;}
    if(a.startsWith('toggle-account:')){s.accountEdit=a.slice(15);const current=account(s.accountEdit);if(current.enabled)open('account-disable');else{current.enabled=true;settleWaiting(s.results.filter(r=>r.target===current.id));render();toast('已启用原目标身份；未加入新的批次');}return;}
    if(a.startsWith('remove-account:')){s.accountEdit=a.slice(15);open('account-remove');return;}
    if(a.startsWith('op:')){const op=a.slice(3);if(op==='stitch'&&s.selected.size<2)return toast('拼接需要至少两张图片');if(s.op!==op){s.op=op;if(op==='stitch')s.order=[...s.selected];invalidate();}render();return;}
    if(a.startsWith('pause-older:')||a.startsWith('cancel-older:')){const cancel=a.startsWith('cancel-older:'),items=s.batches[Number(a.split(':')[1])].items,resume=items.some(r=>r.state==='paused');for(const r of items)if(pendingState(r.state)){r.state=cancel?'canceled':resume?'waiting':'paused';r.attempts.at(-1).state=r.state;}if(!cancel)settleWaiting(items);render();return;}
    if(a.startsWith('retry-older:')){retryResults(s.batches[Number(a.slice(12))].items);return;}
    if(a.startsWith('copy-older:')){s.copyResults=s.batches[Number(a.slice(11))].items.filter(r=>r.state==='succeeded');open('batch-links');return;}
    if(a.startsWith('move:')){const [,id,step]=a.split(':');const i=s.order.indexOf(Number(id)),j=i+Number(step);if(j>=0&&j<s.order.length){[s.order[i],s.order[j]]=[s.order[j],s.order[i]];invalidate();render();}return;}
    switch(a){
      case 'select-on':s.selecting=true;render();break;
      case 'select-off':close();s.selecting=false;s.selected.clear();render();break;
      case 'select-all':s.selected=new Set((s.page==='picker'?s.images.filter(p=>p.name.toLowerCase().includes(s.query.toLowerCase())):filtered()).map(p=>p.id));close();render();break;
      case 'clear-search':s.query='';s.filter='all';render();break;
      case 'import':open('import');break;
      case 'mock-photo-import':if(s.scenario==='permission'){toast('照片权限受限，请改用文件来源');break;}if(s.scenario==='cloud-error'&&s.importAttempts++===0){toast('云照片获取失败，原文件与图库保留，请重试');break;}onAction('mock-import');break;
      case 'mock-import':{const id=s.nextAssetId++;s.images.push({id,name:'新导入_示例.jpg',size:'2.2 MB',linked:false,sprite:0});if(mode==='m2')s.selected.add(id);close();render();toast('独立副本已添加（演示），用户原文件保留');break;}
      case 'compress':edit('compress');break;
      case 'stitch':edit('stitch');break;
      case 'upload':if(!s.selected.size){toast('先选择图片');break;}setUpload('original',[...s.selected]);open('upload');break;
      case 'detail-edit':s.selected=new Set([s.focus]);edit('crop');break;
      case 'detail-upload':setUpload(image(s.focus).kind==='processed'?'saved':'original',[s.focus]);open('upload');break;
      case 'detail-links':{const r=s.results.find(r=>r.state==='succeeded'&&r.sourceIds.includes(s.focus));if(r){s.linkResult=r.id;open('links');}else toast('暂无成功链接');break;}
      case 'favorite':image(s.focus).favorite=!image(s.focus).favorite;render();toast(image(s.focus).favorite?'已收藏':'已取消收藏');break;
      case 'delete':open('delete');break;
      case 'confirm-delete':if(s.results.some(r=>['waiting','paused','authorization','unknown'].includes(r.state)&&r.sourceIds.includes(s.focus))||s.focus===7&&!s.canceled||s.draftBatch?.selected.includes(s.focus)||s.draftBatch?.outputObjects.some(p=>p.savedAssetId===s.focus)){toast('图片仍被活跃任务或处理批次依赖，先取消任务或清空批次');break;}s.images=s.images.filter(p=>p.id!==s.focus);s.selected.delete(s.focus);close();go('library');toast('已删除本机演示记录，原文件与远程文件保留');break;
      case 'more-selected':open('more-selected');break;
      case 'selected-detail':if(!s.selected.size){toast('尚未选择图片');break;}s.focus=[...s.selected][0];s.returnPage='library';s.selecting=false;close();go('detail');break;
      case 'picker-next':if(s.selected.size)edit(s.op);break;
      case 'resume':resumeBatch();break;
      case 'clear-batch':s.draftBatch=null;s.selected.clear();invalidate();render();toast('已清空处理批次，永久图片与远程结果保留');break;
      case 'clear-selection':s.selected.clear();render();break;
      case 'generate':if(s.op==='compress'&&(!Number.isInteger(Number(s.length))||Number(s.length)<1||Number(s.length)>12000)){toast('最长边应为 1–12000 的整数');break;}if(s.op==='stitch'&&(!Number.isInteger(Number(s.gap))||Number(s.gap)<0||Number(s.gap)>200)){toast('间距应为 0–200 的整数');break;}if(s.format==='JPEG'&&(s.op==='crop'?[[...s.selected][0]]:[...s.selected]).some(id=>image(id).name.endsWith('.png'))){open('flatten');break;}s.outputObjects=outputObjects();s.output=true;s.saved=false;render();toast(`${s.outputObjects.length} 个演示结果已生成，尚未永久保存`);break;
      case 'confirm-generate':close();s.outputObjects=outputObjects();s.output=true;s.saved=false;render();toast('已确认白色背景（演示）');break;
      case 'save-result':if(s.scenario==='save-error'&&s.saveAttempts++===0){toast('保存失败，临时结果仍保留，可重试或导出');break;}if(!s.saved&&s.outputObjects.length){for(const p of s.outputObjects){const id=s.nextAssetId++;p.savedAssetId=id;s.images.push({...p,id,sourceIds:[...p.sourceIds]});for(const r of s.results)if(r.versionId===p.versionId&&!r.sourceIds.includes(id))r.sourceIds.push(id);}s.saved=true;render();toast(`${s.outputObjects.length} 个处理副本已保存到演示图库`);}break;
      case 'export-result':s.exported=true;render();toast('已演示导出副本，未写入设备文件');break;
      case 'output-upload':setUpload('processed');if(mode==='m2')go('targets');else open('upload');break;
      case 'skip-processing':setUpload('original',[...s.selected]);go('targets');break;
      case 'start-upload':startBatch();break;
      case 'resume-authorized':settleWaiting(s.batch);render();toast('仅核对原目标条件；不会改派其他账号');break;
      case 'pause-current':{const resume=s.batch.some(r=>r.state==='paused');for(const r of s.batch)if(pendingState(r.state)){r.state=resume?'waiting':'paused';r.attempts.at(-1).state=r.state;}settleWaiting(s.batch);render();break;}
      case 'cancel-current':for(const r of s.batch)if(pendingState(r.state)){r.state='canceled';r.attempts.at(-1).state='canceled';}render();toast('已取消本次排队，永久副本与已有成功结果保留');break;
      case 'online':s.offline=false;settleWaiting(s.results);render();toast('已演示恢复联网，原排队记录继续处理');break;
      case 'copy-one':close();toast('链接复制反馈已演示，未写入剪贴板');break;
      case 'copy-history':s.copyResults=s.results.filter(r=>r.state==='succeeded'&&Number(r.id.slice(7))<=4);open('batch-links');break;
      case 'copy-batch':s.copyResults=(s.batch.length?s.batch:s.results).filter(r=>r.state==='succeeded');if(!s.copyResults.length){toast('没有成功链接可复制');break;}open('batch-links');break;
      case 'copy-summary':close();toast('已演示复制成功链接，失败与待确认项未混入');break;
      case 'pause':s.paused=!s.paused;render();break;
      case 'cancel':s.canceled=true;render();toast('已取消后续任务，本机副本与已成功链接保留');break;
      case 'retry':retryResults(articleResults());break;
      case 'resume-history':settleWaiting(articleResults());render();toast('只检查历史原账号身份，不改派新账号');break;
      case 'cancel-history':for(const r of articleResults())if(pendingState(r.state)){r.state='canceled';r.attempts.at(-1).state='canceled';}render();toast('已取消历史等待项；原成功结果保留');break;
      case 'retry-batch':retryResults(s.batch);break;
      case 'unknown':open('unknown');break;
      case 'unknown-retry':if(!document.querySelector('#duplicate-risk').checked){toast('请先确认重复上传风险');break;}s.unknownRetransmitted=true;setUpload('original',[4]);const previous=[...s.targets];s.targets=['catbox'];const created=startBatch();s.targets=previous;if(created)toast('已创建新的演示上传，原待确认记录保留');break;
      case 'credential':s.accountEdit='imgbb';open('credential');break;
      case 'add-account':s.accountEdit=null;open('credential');break;
      case 'save-credential':{const name=document.querySelector('#account-name').value.trim(),hasNewCredential=!!document.querySelector('#mock-key').value.trim(),a=account(s.accountEdit);if(!name)return toast('请输入账号显示名称');if(!a&&!hasNewCredential)return toast('请输入任意演示凭据');if(a){a.name=name;if(hasNewCredential){a.hasCredential=true;a.validCredential=true;a.status='unverified';}}else{s.accounts.push({id:'account-'+s.nextAccountId++,provider:document.querySelector('#account-provider').value,name,anonymous:false,enabled:true,hasCredential:true,validCredential:true,status:'unverified'});}close();render();toast('示例配置已保存；未存储真实凭据，也未验证服务');break;}
      case 'confirm-disable-account':{const a=account(s.accountEdit);a.enabled=false;suspendAccount(a.id);close();render();toast('已停用此身份，历史结果保留');break;}
      case 'confirm-remove-account':{const a=account(s.accountEdit);a.deleted=true;a.enabled=false;a.hasCredential=false;a.validCredential=false;suspendAccount(a.id);s.targets=s.targets.filter(id=>id!==a.id);close();render();toast('配置已移除；历史结果仍可查找');break;}
      case 'clear-link-search':s.linkQuery='';s.linkTarget='all';s.linkVersion='all';render();break;
      case 'copy-filtered':s.copyResults=filteredLinks();if(s.copyResults.length)open('batch-links');break;
      case 'catbox-info':case 'cache':case 'backup':case 'restore':case 'diagnostics':case 'discard':open(a);break;
      case 'confirm-cache':s.cacheClean=true;close();render();toast('过期缓存已清理，永久副本与活跃依赖保留');break;
      case 'confirm-backup':close();toast('已演示完整备份导出，未生成备份文件');break;
      case 'confirm-restore':s.restored=true;close();render();toast('恢复确认已演示，未修改设备数据');break;
      case 'copy-diagnostics':close();toast('脱敏诊断复制反馈已演示');break;
      case 'save-settings':s.preferences={...s.draft};s.settingSaved=true;render();toast('偏好已保留在演示会话');break;
      case 'swap-order':s.order.reverse();invalidate();render();break;
      case 'confirm-discard':rememberBatch();close();go(mode==='m2'?'home':'library');break;
      case 'close':close();break;
    }
  }
  document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)onAction(el.dataset.action);});
  document.addEventListener('input',e=>{if(e.target.tagName==='INPUT'&&['length','gap','quality'].includes(e.target.dataset.field)){const f=e.target.dataset.field,hadOutput=s.output;s[f]=e.target.value;invalidate();rememberBatch();if(hadOutput){render();document.querySelector('[data-field="'+f+'"]').focus();}}if(e.target.id==='link-search'){const pos=e.target.selectionStart;s.linkQuery=e.target.value;render();const input=document.querySelector('#link-search');input.focus();input.setSelectionRange(pos,pos);}if(e.target.id==='search'){const pos=e.target.selectionStart;s.query=e.target.value;render();const input=document.querySelector('#search');input.focus();input.setSelectionRange(pos,pos);}});
  document.addEventListener('change',e=>{const t=e.target;if(t.id==='link-target'||t.id==='link-version'){s[t.id==='link-target'?'linkTarget':'linkVersion']=t.value;render();return;}if(t.dataset.target){s.targets=t.checked?[...new Set([...s.targets,t.dataset.target])]:s.targets.filter(v=>v!==t.dataset.target);}if(t.dataset.field){const f=t.dataset.field;if(['network','concurrency','retention'].includes(f)){s.draft[f]=t.value;s.settingSaved=false;}else{s[f]=t.value;invalidate();render();}}});
  document.addEventListener('keydown',e=>{if(!s.modal)return;if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const els=[...document.querySelectorAll('.sheet button,.sheet input,.sheet select,.sheet a')].filter(el=>!el.disabled);if(!els.length)return;const idx=els.indexOf(document.activeElement);if(e.shiftKey&&idx<=0){e.preventDefault();els.at(-1).focus();}else if(!e.shiftKey&&idx===els.length-1){e.preventDefault();els[0].focus();}}});
  if(['editor','targets','receipt'].includes(s.page)){s.selected=new Set([1,2]);setUpload('original',[1,2]);}
  if(s.page==='picker')s.selecting=true;
  render();
})();
