// Generated by tool/versioning.dart from versions.json. Do not edit.
part of 'app_versions.dart';

const imageHubVersions = AppVersionCatalog(
  kernel: KernelVersion('0.1.0', 1),
  platforms: {
    AppPlatform.windows: PlatformVersion('0.1.0', 1),
    AppPlatform.macos: PlatformVersion('0.1.0', 1),
    AppPlatform.android: PlatformVersion('0.1.0', 1),
    AppPlatform.ios: PlatformVersion('0.1.0', 1),
  },
);
