import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

// Run from app/: dart run tool/generate_case_folding.dart [--check]
// The checked-in source is downloaded once from the fixed official URL below.
// No network access or package installation is performed by this generator.
const sourceUrl = 'https://www.unicode.org/Public/17.0.0/ucd/CaseFolding.txt';
const sourceSha256 =
    'ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183';

Future<void> main(List<String> arguments) async {
  if (arguments.any((argument) => argument != '--check')) {
    throw ArgumentError(
      'Usage: dart run tool/generate_case_folding.dart [--check]',
    );
  }
  final source = File('tool/unicode/CaseFolding-17.0.0.txt');
  final bytes = await source.readAsBytes();
  if (sha256.convert(bytes).toString() != sourceSha256) {
    throw StateError('Unicode 17.0.0 CaseFolding source SHA-256 mismatch.');
  }
  final mappings = <int, List<int>>{};
  for (final line in const LineSplitter().convert(utf8.decode(bytes))) {
    final record = line.split('#').first.trim();
    if (record.isEmpty) continue;
    final fields = record.split(';').map((value) => value.trim()).toList();
    if (fields[1] != 'C' && fields[1] != 'F') continue;
    final scalar = int.parse(fields[0], radix: 16);
    if (mappings.containsKey(scalar)) {
      throw StateError('Duplicate C/F record for U+${fields[0]}.');
    }
    mappings[scalar] = fields[2]
        .split(RegExp(r'\s+'))
        .map((value) => int.parse(value, radix: 16))
        .toList();
  }
  final generated = StringBuffer()
    ..writeln('// GENERATED by tool/generate_case_folding.dart. Do not edit.')
    ..writeln('// Source: $sourceUrl')
    ..writeln('// Source SHA-256: $sourceSha256')
    ..writeln('// Unicode data copyright Unicode, Inc.; terms:')
    ..writeln('// https://www.unicode.org/terms_of_use.html')
    ..writeln('// Default full folding uses C/F records only; excludes S/T.')
    ..writeln()
    ..writeln("const unicodeCaseFoldingVersion = '17.0.0';")
    ..writeln('const unicodeCaseFoldingSourceSha256 =')
    ..writeln("    '$sourceSha256';")
    ..writeln()
    ..writeln('String unicodeDefaultCaseFold(String input) {')
    ..writeln('  final output = StringBuffer();')
    ..writeln('  for (final scalar in input.runes) {')
    ..writeln(
      '    output.write(_defaultFullMappings[scalar] ?? String.fromCharCode(scalar));',
    )
    ..writeln('  }')
    ..writeln('  return output.toString();')
    ..writeln('}')
    ..writeln()
    ..writeln('const _defaultFullMappings = <int, String>{');
  final keys = mappings.keys.toList()..sort();
  for (final scalar in keys) {
    final escaped = mappings[scalar]!.map((value) {
      final hex = value.toRadixString(16);
      return value <= 0xffff ? '\\u${hex.padLeft(4, '0')}' : '\\u{$hex}';
    }).join();
    generated.writeln("  0x${scalar.toRadixString(16)}: '$escaped',");
  }
  generated.writeln('};');
  final target = File('lib/core/unicode_case_folding.dart');
  if (arguments.contains('--check')) {
    if (await target.readAsString() != generated.toString()) {
      throw StateError('Generated CaseFolding table is out of date.');
    }
    stdout.writeln('Unicode 17.0.0: ${mappings.length} C/F mappings verified.');
  } else {
    await target.writeAsString(generated.toString(), flush: true);
    stdout.writeln(
      'Generated ${mappings.length} C/F mappings from pinned source.',
    );
  }
}
